### ISSUE TITLE
Promise Errors with switches/lights and RF Bridge

### ISSUE THREAD

**Issue by ygbr** [bwp91/homebridge-ewelink#101]
**What issue do you have? Please be as thorough and explicit as possible.**

After updating to 3.1.4 when I change the state of Sonoff T1 switches it generates a lot of JS errors related to Promises.

**Details of your setup.**
Homebridge

Which version of Homebridge/HOOBS do you have?

Homebridge 1.2.3

Which version of this plugin (homebridge-ewelink) do you have?

3.1.4

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

```
(node:542) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'externalMultiLightUpdate' of undefined
    at eWeLink.refreshAccessory (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:926:29)
    at eWeLink.receiveDeviceUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:1035:17)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:96:48)
    at EventEmitter.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLinkLAN.js:101:28
    at Array.forEach (<anonymous>)
    at DnsSd.dns.ondata (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLinkLAN.js:53:12)
    at DnsSd._receivePacket (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/node-dns-sd/lib/dns-sd.js:567:9)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/node-dns-sd/lib/dns-sd.js:516:9)
    at Socket.emit (events.js:315:20)
(node:542) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

```

**Comment by bwp91** [comment]
Hi, just to check, have you restarted homebridge since updating?

**Comment by ygbr** [comment]
Hi, yes I always restart after updating plugins.

I have also tried to restart the entire RPi a few times to see if the error goes away, but that didn't do it.

Let me know if I can help in any way.

**Comment by bwp91** [comment]
Which sonoff devices do you have?
If you can refer to them by product model that would be super helpful

**Comment by ygbr** [comment]
The issue is happening with both Sonoff T1 - US (3 gang switches) that I have.

The model shown on eWeLink is: T1 3C

They are running the latest firmware (PSF-B04-GL)

They are both configured with Lan Mode enabled.

**Comment by bwp91** [comment]
Okay I can't immediately think of why this is happening.
Will need to troubleshoot more - would you be happy to message to me on the homebridge discord?
https://discord.gg/7X36mdw

**Comment by bwp91** [comment]
Do you have the `hideMasters` config option set to true?

**Comment by ygbr** [comment]
Hi, 
I do! I hide the master switches for the t1 devices in order to prevent them to show on the home app.

Sorry I wasn’t able to join discord earlier.

Tks

**Comment by bwp91** [comment]
I'd be interested to see if v3.1.5 has fixed this for you?

**Comment by traxinv** [comment]
Morning, im on the latest version also getting the same errors:

(node:14148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 33)
(node:14148) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'externalRFUpdate' of undefined
    at eWeLink.refreshAccessory (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\eWeLink.js:950:27)
    at eWeLink.receiveDeviceUpdate (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\eWeLink.js:1048:17)
    at EventEmitter.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\eWeLink.js:92:48)
    at EventEmitter.emit (events.js:311:20)
    at C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\eWeLinkLAN.js:101:28
    at Array.forEach (<anonymous>)
    at DnsSd.dns.ondata (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-ewelink\lib\eWeLinkLAN.js:53:12)
    at DnsSd._receivePacket (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-ewelink\node_modules\node-dns-sd\lib\dns-sd.js:567:9)
    at Socket.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge-ewelink\node_modules\node-dns-sd\lib\dns-sd.js:516:9)
    at Socket.emit (events.js:311:20)
(node:14148) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 34)

**Comment by bwp91** [comment]
@traxinv its the RF Bridge causing this error. this is a device that i haven't been able to test with the latest updates since I don't own it.
Would you be happy to share your rf bridge with my ewelink account so I can look into this more thoroughly?

**Comment by traxinv** [comment]
Cool sure thing, send me your email please via DM and i will share it with you

**Comment by bwp91** [comment]
@traxinv where abouts in the world are you from? ie country or continent?

**Comment by traxinv** [comment]
@bwp91 South Africa

**Comment by bwp91** [comment]
thanks, deleted that comment now i know

**Comment by bwp91** [comment]
please share to
bwp91@icloud.com

and it would be useful if you could join the homebridge discord so i could message you?

**Comment by traxinv** [comment]
shared, and sent you a message on discord.

**Comment by bwp91** [comment]
Closing this now as I am confident these issues are fixed in the latest version of the plugin.
Thanks!
