### ISSUE TITLE
Error after reinstalling homebridge

### ISSUE THREAD

**Issue by Stonedbat** [bwp91/homebridge-ewelink#103]
**What issue do you have? Please be as thorough and explicit as possible.**
Hi. My HomeBridge instal encountered a fatal error and I needed to start from the ground up. I used the Homebridge SD card image and a recent backup before I had Sonoff devices. I installed the plugin through Config-ui-x but my Sonoff devices will not appear in Homebridge. All other devices appear normally.
...

**Details of your setup.**
Do you use Homebridge or HOOBS?
HomeBridge
...

Which version of Homebridge/HOOBS do you have?
1.2.3
...

Which version of this plugin (homebridge-ewelink) do you have?
Tried with 3.1.5 and 3.1.6
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

```
[9/30/2020, 00:18:02] [eWeLink] Initializing eWeLink platform...
[9/30/2020, 00:18:04] [eWeLink] Plugin has finished initialising. Synching with eWeLink.
[9/30/2020, 00:18:04] [eWeLink] Sending HTTP getHost request. This text is yellow for clarity.
{
  "appid": "oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq",
  "country_code": "+353",
  "nonce": "9ssituao",
  "ts": 1601421484,
  "version": 8
}
[9/30/2020, 00:18:09] [eWeLink] HTTP API host received [eu-apia.coolkit.cc].
[9/30/2020, 00:18:09] [eWeLink] Sending HTTP login request. This text is yellow for clarity.
{
  "countryCode": "+353",
  "password": "**hidden**",
  "email": "**hidden**"
}
[9/30/2020, 00:18:13] [eWeLink] Web socket host received [eu-pconnect1.coolkit.cc].
[9/30/2020, 00:18:14] [eWeLink] Sending WS login request. This text is yellow for clarity.
{
  "action": "userOnline",
  "apikey": "**hidden**",
  "appid": "oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq",
  "at": "**hidden**",
  "nonce": "yj8or3q8",
  "sequence": "1601421494615",
  "ts": 1601421494,
  "userAgent": "app",
  "version": 8
}
[9/30/2020, 00:18:17] [eWeLink] [0] eWeLink devices loaded from the Homebridge cache.
[9/30/2020, 00:18:17] [eWeLink] [3] primary devices loaded from your eWeLink account.
[9/30/2020, 00:18:17] [eWeLink] ************** Cannot load homebridge-ewelink **************
[9/30/2020, 00:18:17] [eWeLink] TypeError: Cannot read property 'uiid' of undefined
    at eWeLink.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:144:50)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:90:44
    at Map.forEach (<anonymous>:null:null)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:90:26
    at eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:116:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

[9/30/2020, 00:18:17] [eWeLink] ************************************************************
[9/30/2020, 00:18:17] [eWeLink] LAN monitoring gracefully stopped.
(node:8214) UnhandledPromiseRejectionWarning: Error: dropMembership EADDRNOTAVAIL
    at Socket.dropMembership (dgram.js:835:11)
    at /usr/local/lib/node_modules/homebridge-ewelink/node_modules/node-dns-sd/lib/dns-sd.js:433:13
    at Array.forEach (<anonymous>:null:null)
    at DnsSd._dropMembership (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/node-dns-sd/lib/dns-sd.js:432:28)
    at /usr/local/lib/node_modules/homebridge-ewelink/node_modules/node-dns-sd/lib/dns-sd.js:527:8
    at new Promise (<anonymous>:null:null)
    at DnsSd._stopListening (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/node-dns-sd/lib/dns-sd.js:526:16)
    at /usr/local/lib/node_modules/homebridge-ewelink/node_modules/node-dns-sd/lib/dns-sd.js:467:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:8214) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:8214) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[9/30/2020, 00:18:17] [eWeLink] Web socket gracefully closed.
```

**Comment by bwp91** [comment]
Hi, which ewelink device types do you have?

**Comment by bwp91** [comment]
@Stonedbat I have released v3.1.7 which should stop the errors from showing.

You seem to have a device which does not follow the "standard" data format that is sent from ewelink to the plugin. So the new release will skip loading this certain device and so not show the errors that appeared before.

I would be interested to know which devices you have, as I asked before, so I could look into getting it to appear in Homebridge.

**Comment by Stonedbat** [comment]
Hey. I have 2 Sonoff BasicR2’s with the latest firmware: 3.5.0. It’s was working before I had to reinstall homebridge.

**Comment by bwp91** [comment]
In the logs above it says you have 3 devices in your ewelink account?

**Comment by Stonedbat** [comment]
Yeah, I was just looking at that myself. I assume is because I have grouped them in the App.
![0C0780AF-FA69-4419-B2A0-A015B4727EB7](https://user-images.githubusercontent.com/72110612/94652921-a8aa3400-02f2-11eb-945f-46de5d35693d.png)

**Comment by bwp91** [comment]
Ah that’s probably what it was 😄

**Comment by bwp91** [comment]
Is it working now with the latest update?

**Comment by Stonedbat** [comment]
I was just checking that now to. Haha! Yep, I updated and it’s working perfectly! Thanks so much!

**Comment by bwp91** [comment]
Excellent. Im glad there was an explanation for this!
