### ISSUE TITLE
Error after homebridge update verion 1.2.3

### ISSUE THREAD

**Issue by JacoHarms** [bwp91/homebridge-ewelink#105]
After update EWELINK does not work anymore.

I use Hombridge running raspberry Pi

Running homebridge-ewelink v3.2.1

below is last log 

[10/2/2020, 17:32:22] Homebridge is running on port 51000.
[10/2/2020, 17:32:22] [Broadlink RM] Sony Amp On/Off getSwitchState: false
[10/2/2020, 17:32:22] [Broadlink RM] [INFO] Discovered Broadlink RM Mini (2737) at 10.1.1.24 (c8:f7:42:83:81:c3)
[10/2/2020, 17:32:22] [Broadlink RM] Sony BD getSwitchState: false
[10/2/2020, 17:32:22] [Broadlink RM] Sony SAT getSwitchState: false
[10/2/2020, 17:32:22] [Broadlink RM] Sony TV getSwitchState: false
[10/2/2020, 17:32:22] [Broadlink RM] AMP Volume Down getSwitchState: false
[10/2/2020, 17:32:22] [Broadlink RM] AMP Volume Up getSwitchState: false
[10/2/2020, 17:32:23] [eWeLink] HTTP API host received [eu-apia.coolkit.cc].
[10/2/2020, 17:32:23] [eWeLink] Sending HTTP login request.
[10/2/2020, 17:32:24] [TuyaWebPlatform] Existing Accessory found [Name: Kaylins Room] [Tuya ID: 20142465c82b9658b978] [HomeBridge ID: f4819433-540a-4059-bf40-9f6a3f9c368a]
[10/2/2020, 17:32:24] [TuyaWebPlatform] [Kaylins Room] Characteristic.On - Enabled
[10/2/2020, 17:32:24] [TuyaWebPlatform] Existing Accessory found [Name: Edwins Room] [Tuya ID: 20142465c82b9658b8d3] [HomeBridge ID: 863f867f-702f-48d6-bc1c-9e74588f1adc]
[10/2/2020, 17:32:24] [TuyaWebPlatform] [Edwins Room] Characteristic.On - Enabled
[10/2/2020, 17:32:24] [TuyaWebPlatform] Existing Accessory found [Name: Main Bathroom] [Tuya ID: 20142465c82b9658b91c] [HomeBridge ID: 923d2a46-d158-4a4d-9d72-579f0e952d42]
[10/2/2020, 17:32:24] [TuyaWebPlatform] [Main Bathroom] Characteristic.On - Enabled
[10/2/2020, 17:32:24] [TuyaWebPlatform] Existing Accessory found [Name: Switch 1] [Tuya ID: 62474317c82b9658be20_1] [HomeBridge ID: e1b477cd-ca7f-48ab-8e4f-e5ef4604b14c]
[10/2/2020, 17:32:24] [TuyaWebPlatform] [Switch 1] Characteristic.On - Enabled
[10/2/2020, 17:32:24] [TuyaWebPlatform] Existing Accessory found [Name: Switch 2] [Tuya ID: 62474317c82b9658be20_2] [HomeBridge ID: 2ec3a890-30c1-4832-9a4d-d0e54d2d7e86]
[10/2/2020, 17:32:24] [TuyaWebPlatform] [Switch 2] Characteristic.On - Enabled
[10/2/2020, 17:32:28] [eWeLink] Web socket host received [eu-pconnect7.coolkit.cc].
[10/2/2020, 17:32:29] [eWeLink] Sending WS login request.
[10/2/2020, 17:32:31] [eWeLink] [23] eWeLink devices loaded from the Homebridge cache.
[10/2/2020, 17:32:31] [eWeLink] [14] primary devices loaded from your eWeLink account.
[10/2/2020, 17:32:31] [eWeLink]  → [Gate] initialised and found locally with IP [10.1.1.74].
[10/2/2020, 17:32:31] [eWeLink]  → [Motion Bathroom ] initialised but LAN mode unavailable as device is unreachable.
[10/2/2020, 17:32:31] [eWeLink] ************* Cannot load homebridge-ewelink *************
[10/2/2020, 17:32:31] [eWeLink] TypeError: Cannot read property 'displayName' of undefined
    at eWeLink.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:375:71)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:44
    at Map.forEach (<anonymous>:null:null)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:26
    at eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:103:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Catching error on dropMembership: {"errno":"EADDRNOTAVAIL","code":"EADDRNOTAVAIL","syscall":"dropMembership"}
[10/2/2020, 17:32:31] [eWeLink] LAN monitoring gracefully stopped.
[10/2/2020, 17:32:31] [eWeLink] Web socket gracefully closed.

**Comment by bwp91** [comment]
Hi,
Please update to v3.2.2. This will fix the error you are seeing but there is a good possibility you will see another error which will be more specific to why something isn't working correctly.
Please let me know

**Comment by JacoHarms** [comment]
Hi Ben

Thank you, but after restart still getting the same error

[cid:image001.png@01D698E5.3A1892B0]

[cid:image002.png@01D698E5.3A1892B0]

**Comment by JacoHarms** [comment]
Here is the log

[10/2/2020, 17:57:24] Homebridge is running on port 51000.
[10/2/2020, 17:57:24] [Broadlink RM] Sony Amp On/Off getSwitchState: false
[10/2/2020, 17:57:24] [Broadlink RM] Sony BD getSwitchState: false
[10/2/2020, 17:57:24] [Broadlink RM] Sony SAT getSwitchState: false
[10/2/2020, 17:57:24] [Broadlink RM] Sony TV getSwitchState: false
[10/2/2020, 17:57:24] [Broadlink RM] AMP Volume Down getSwitchState: false
[10/2/2020, 17:57:24] [Broadlink RM] AMP Volume Up getSwitchState: false
[10/2/2020, 17:57:24] [Broadlink RM] [INFO] Discovered Broadlink RM Mini (2737) at 10.1.1.24 (c8:f7:42:83:81:c3)
[10/2/2020, 17:57:25] [eWeLink] HTTP API host received [eu-apia.coolkit.cc].
[10/2/2020, 17:57:25] [eWeLink] Sending HTTP login request.
[10/2/2020, 17:57:26] [TuyaWebPlatform] Existing Accessory found [Name: Kaylins Room] [Tuya ID: 20142465c82b9658b978] [HomeBridge ID: f4819433-540a-4059-bf40-9f6a3f9c368a]
[10/2/2020, 17:57:26] [TuyaWebPlatform] [Kaylins Room] Characteristic.On - Enabled
[10/2/2020, 17:57:26] [TuyaWebPlatform] Existing Accessory found [Name: Edwins Room] [Tuya ID: 20142465c82b9658b8d3] [HomeBridge ID: 863f867f-702f-48d6-bc1c-9e74588f1adc]
[10/2/2020, 17:57:26] [TuyaWebPlatform] [Edwins Room] Characteristic.On - Enabled
[10/2/2020, 17:57:26] [TuyaWebPlatform] Existing Accessory found [Name: Main Bathroom] [Tuya ID: 20142465c82b9658b91c] [HomeBridge ID: 923d2a46-d158-4a4d-9d72-579f0e952d42]
[10/2/2020, 17:57:26] [TuyaWebPlatform] [Main Bathroom] Characteristic.On - Enabled
[10/2/2020, 17:57:26] [TuyaWebPlatform] Existing Accessory found [Name: Switch 1] [Tuya ID: 62474317c82b9658be20_1] [HomeBridge ID: e1b477cd-ca7f-48ab-8e4f-e5ef4604b14c]
[10/2/2020, 17:57:26] [TuyaWebPlatform] [Switch 1] Characteristic.On - Enabled
[10/2/2020, 17:57:26] [TuyaWebPlatform] Existing Accessory found [Name: Switch 2] [Tuya ID: 62474317c82b9658be20_2] [HomeBridge ID: 2ec3a890-30c1-4832-9a4d-d0e54d2d7e86]
[10/2/2020, 17:57:26] [TuyaWebPlatform] [Switch 2] Characteristic.On - Enabled
[10/2/2020, 17:57:30] [eWeLink] Web socket host received [eu-pconnect3.coolkit.cc].
[10/2/2020, 17:57:32] [eWeLink] Sending WS login request.
[10/2/2020, 17:57:33] [eWeLink] [23] eWeLink devices loaded from the Homebridge cache.
[10/2/2020, 17:57:33] [eWeLink] [14] primary devices loaded from your eWeLink account.
[10/2/2020, 17:57:33] [eWeLink]  → [Gate] initialised and found locally with IP [10.1.1.74].
[10/2/2020, 17:57:33] [eWeLink]  → [Motion Bathroom ] initialised but LAN mode unavailable as device is unreachable.
[10/2/2020, 17:57:33] [eWeLink] ************* Cannot load homebridge-ewelink *************
[10/2/2020, 17:57:33] [eWeLink] TypeError: Cannot read property 'displayName' of undefined
    at eWeLink.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:385:71)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:44
    at Map.forEach (<anonymous>:null:null)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:26
    at eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:103:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

Catching error on dropMembership: {"errno":"EADDRNOTAVAIL","code":"EADDRNOTAVAIL","syscall":"dropMembership"}
[10/2/2020, 17:57:33] [eWeLink] LAN monitoring gracefully stopped.
[10/2/2020, 17:57:34] [eWeLink] Web socket gracefully closed.
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Main Bathroom] - Requesting device state
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Main Bathroom] - Creating new debounced promise
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Main Bathroom] - Triggering debouncedDeviceStateRequest
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 1] - Requesting device state
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 1] - Creating new debounced promise
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 1] - Triggering debouncedDeviceStateRequest
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 2] - Requesting device state
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 2] - Creating new debounced promise
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 2] - Triggering debouncedDeviceStateRequest
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Kaylins Room] - Requesting device state
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Kaylins Room] - Creating new debounced promise
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Kaylins Room] - Triggering debouncedDeviceStateRequest
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Edwins Room] - Requesting device state
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Edwins Room] - Creating new debounced promise
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Edwins Room] - Triggering debouncedDeviceStateRequest
[10/2/2020, 17:57:55] [Broadlink RM] Sony Amp On/Off getSwitchState: false
[10/2/2020, 17:57:55] [Broadlink RM] Sony BD getSwitchState: false
[10/2/2020, 17:57:55] [Broadlink RM] Sony SAT getSwitchState: false
[10/2/2020, 17:57:55] [Broadlink RM] Sony TV getSwitchState: false
[10/2/2020, 17:57:55] [Broadlink RM] AMP Volume Down getSwitchState: false
[10/2/2020, 17:57:55] [Broadlink RM] AMP Volume Up getSwitchState: false
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Main Bathroom] - Unsetting debouncedDeviceStateRequestPromise
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Main Bathroom] - Resolving resolveDeviceStateRequest from cache
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Main Bathroom] Characteristic.On - [GET] true
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 1] - Unsetting debouncedDeviceStateRequestPromise
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 1] - Resolving resolveDeviceStateRequest from cache
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 1] Characteristic.On - [GET] true
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 2] - Unsetting debouncedDeviceStateRequestPromise
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 2] - Resolving resolveDeviceStateRequest from cache
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Switch 2] Characteristic.On - [GET] true
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Kaylins Room] - Unsetting debouncedDeviceStateRequestPromise
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Kaylins Room] - Resolving resolveDeviceStateRequest from cache
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Kaylins Room] Characteristic.On - [GET] true
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Edwins Room] - Unsetting debouncedDeviceStateRequestPromise
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Edwins Room] - Resolving resolveDeviceStateRequest from cache
[10/2/2020, 17:57:55] [TuyaWebPlatform] [Edwins Room] Characteristic.On - [GET] true
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Main Bathroom] - Requesting device state
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Main Bathroom] - Creating new debounced promise
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Main Bathroom] - Triggering debouncedDeviceStateRequest
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 1] - Requesting device state
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 1] - Creating new debounced promise
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 1] - Triggering debouncedDeviceStateRequest
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 2] - Requesting device state
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 2] - Creating new debounced promise
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 2] - Triggering debouncedDeviceStateRequest
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Kaylins Room] - Requesting device state
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Kaylins Room] - Creating new debounced promise
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Kaylins Room] - Triggering debouncedDeviceStateRequest
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Edwins Room] - Requesting device state
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Edwins Room] - Creating new debounced promise
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Edwins Room] - Triggering debouncedDeviceStateRequest
[10/2/2020, 17:57:58] [Broadlink RM] Sony Amp On/Off getSwitchState: false
[10/2/2020, 17:57:58] [Broadlink RM] Sony BD getSwitchState: false
[10/2/2020, 17:57:58] [Broadlink RM] Sony SAT getSwitchState: false
[10/2/2020, 17:57:58] [Broadlink RM] Sony TV getSwitchState: false
[10/2/2020, 17:57:58] [Broadlink RM] AMP Volume Down getSwitchState: false
[10/2/2020, 17:57:58] [Broadlink RM] AMP Volume Up getSwitchState: false
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Main Bathroom] - Unsetting debouncedDeviceStateRequestPromise
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Main Bathroom] - Resolving resolveDeviceStateRequest from cache
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Main Bathroom] Characteristic.On - [GET] true
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 1] - Unsetting debouncedDeviceStateRequestPromise
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 1] - Resolving resolveDeviceStateRequest from cache
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 1] Characteristic.On - [GET] true
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 2] - Unsetting debouncedDeviceStateRequestPromise
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 2] - Resolving resolveDeviceStateRequest from cache
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Switch 2] Characteristic.On - [GET] true
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Kaylins Room] - Unsetting debouncedDeviceStateRequestPromise
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Kaylins Room] - Resolving resolveDeviceStateRequest from cache
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Kaylins Room] Characteristic.On - [GET] true
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Edwins Room] - Unsetting debouncedDeviceStateRequestPromise
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Edwins Room] - Resolving resolveDeviceStateRequest from cache
[10/2/2020, 17:57:58] [TuyaWebPlatform] [Edwins Room] Characteristic.On - [GET] true

[cid:image001.png@01D698E5.D3D0FD70]

**Comment by bwp91** [comment]
Could I message you directly on the Homebridge discord channel?
https://discord.gg/7X36mdw

**Comment by JacoHarms** [comment]
Thank you Ben, we can but I left home now for a while,

Thank you for the help so far

Jaco Harms
Flexitron SOS

On 02 Oct 2020, at 18:07, Ben <notifications@github.com> wrote:

﻿

Could I message you directly on the Homebridge discord channel?
https://discord.gg/7X36mdw

**Comment by bwp91** [comment]
Okay sure.
If you're able to while you're out, please try v3.2.3

**Comment by JacoHarms** [comment]
Different error in yellow, although my switches are back in homekit.


[10/2/2020, 18:31:22] [eWeLink] [Rf Bridge] could not be initialised as TypeError: Cannot read property 'getService' of undefined
    at eWeLink.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:361:12)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:44
    at Map.forEach (<anonymous>:null:null)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:26
    at eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:103:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
.

[cid:image003.png@01D698EB.1DDFA1A0]

**Comment by bwp91** [comment]
The problematic device is your "Rf Bridge".
Do you have a specific brand and product model for this device that could help me?

**Comment by JacoHarms** [comment]
Hi Ben

Thank you, this is what I bought

[US$16.90 32% OFF]SONOFF ZBBridge Smart Bridge Zigbee3.0 APP Wireless Remote Controller Smart Home Bridge Works With Alexa Google Home Smart Home from Consumer Electronics on banggood https://banggood.app.link/BvAH5apkgab

I have always seen the message that sensor is initialized but LAN mode unavailable  since device is unreachable, although sensor is showing and working most of the times in homekit. Sure it will be in logs I sent you

The RF bridge doesn’t show in home kit, only the sensor, but I am almost sure it showed when I just added it a few updates back

Thanks again for the help


Jaco Harms
Flexitron SOS

On 02 Oct 2020, at 18:48, Ben <notifications@github.com> wrote:

﻿

The problematic device is your "Rf Bridge".
Do you have a specific brand and product model for this device that could help me?

**Comment by bwp91** [comment]
I'll need to look into this more could you contact me on the homebridge discord the link i sent you above?

**Comment by bwp91** [comment]
is this an "RF bridge" or a "zigbee bridge"?

**Comment by bwp91** [comment]
Hi, are you still receiving this error if you update to v3.2.4?

**Comment by JacoHarms** [comment]
Morning Ben. Again thanx for the help,

I joined the discord channel, Jaco#2045. You can message me there if you like

Just update to homebridge-ewelink v3.3.1, and got some new errors, looks like something about hide master switches.

Still getting the issue with the RF bridge.

Other weird thing is, my Homebrdige shows Version 1.1.6?

[10/5/2020, 09:34:26] Homebridge is running on port 51000.
[10/5/2020, 09:34:26] [Broadlink RM] Sony Amp On/Off getSwitchState: false
[10/5/2020, 09:34:26] [Broadlink RM] [INFO] Discovered Broadlink RM Mini (2737) at 10.1.1.24 (c8:f7:42:83:81:c3)
[10/5/2020, 09:34:26] [Broadlink RM] Sony BD getSwitchState: false
[10/5/2020, 09:34:26] [Broadlink RM] Sony SAT getSwitchState: false
[10/5/2020, 09:34:26] [Broadlink RM] Sony TV getSwitchState: false
[10/5/2020, 09:34:26] [Broadlink RM] AMP Volume Down getSwitchState: false
[10/5/2020, 09:34:26] [Broadlink RM] AMP Volume Up getSwitchState: false
[10/5/2020, 09:34:28] [eWeLink] HTTP API host received [eu-apia.coolkit.cc].
[10/5/2020, 09:34:28] [eWeLink] Sending HTTP login request.
[10/5/2020, 09:34:28] [TuyaWebPlatform] Existing Accessory found [Name: Kaylins Room] [Tuya ID: 20142465c82b9658b978] [HomeBridge ID: f4819433-540a-4059-bf40-9f6a3f9c368a]
[10/5/2020, 09:34:28] [TuyaWebPlatform] [Kaylins Room] Characteristic.On - Enabled
[10/5/2020, 09:34:28] [TuyaWebPlatform] Existing Accessory found [Name: Edwins Room] [Tuya ID: 20142465c82b9658b8d3] [HomeBridge ID: 863f867f-702f-48d6-bc1c-9e74588f1adc]
[10/5/2020, 09:34:28] [TuyaWebPlatform] [Edwins Room] Characteristic.On - Enabled
[10/5/2020, 09:34:28] [TuyaWebPlatform] Existing Accessory found [Name: Main Bathroom] [Tuya ID: 20142465c82b9658b91c] [HomeBridge ID: 923d2a46-d158-4a4d-9d72-579f0e952d42]
[10/5/2020, 09:34:28] [TuyaWebPlatform] [Main Bathroom] Characteristic.On - Enabled
[10/5/2020, 09:34:28] [TuyaWebPlatform] Existing Accessory found [Name: Switch 1] [Tuya ID: 62474317c82b9658be20_1] [HomeBridge ID: e1b477cd-ca7f-48ab-8e4f-e5ef4604b14c]
[10/5/2020, 09:34:28] [TuyaWebPlatform] [Switch 1] Characteristic.On - Enabled
[10/5/2020, 09:34:28] [TuyaWebPlatform] Existing Accessory found [Name: Switch 2] [Tuya ID: 62474317c82b9658be20_2] [HomeBridge ID: 2ec3a890-30c1-4832-9a4d-d0e54d2d7e86]
[10/5/2020, 09:34:28] [TuyaWebPlatform] [Switch 2] Characteristic.On - Enabled
[10/5/2020, 09:34:33] [eWeLink] Web socket host received [eu-pconnect5.coolkit.cc].
[10/5/2020, 09:34:34] [eWeLink] Sending WS login request.
[10/5/2020, 09:34:36] [eWeLink] [21] eWeLink devices loaded from the Homebridge cache.
[10/5/2020, 09:34:36] [eWeLink] [16] primary devices loaded from your eWeLink account.
[10/5/2020, 09:34:36] [eWeLink]  → [Motion Passage] initialised but LAN mode unavailable as device is unreachable.
[10/5/2020, 09:34:36] [eWeLink]  → [Deck] initialised but LAN mode unavailable as device is unreachable.
[10/5/2020, 09:34:36] [eWeLink]  → [Gate] initialised and found locally with IP [10.1.1.74].
[10/5/2020, 09:34:36] [eWeLink]  → [Motion Bathroom ] initialised but LAN mode unavailable as device is unreachable.
[10/5/2020, 09:34:36] [eWeLink] [Rf Bridge] could not be initialised as TypeError: Cannot read property 'getService' of undefined
    at eWeLink.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:365:12)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:44
    at Map.forEach (<anonymous>:null:null)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:26
    at eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:103:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
.
[10/5/2020, 09:34:36] [eWeLink]  → [Turkish Large] initialised and found locally with IP [10.1.1.41].
[10/5/2020, 09:34:36] [eWeLink]  → [Turkish Small] initialised and found locally with IP [10.1.1.38].
[10/5/2020, 09:34:36] [eWeLink]  → [Garage door] initialised and found locally with IP [10.1.1.51].
[10/5/2020, 09:34:36] [eWeLink] [Liv2way] could not be initialised as TypeError: (this.config.hideMasters || "").includes is not a function
    at eWeLink.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:218:45)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:44
    at Map.forEach (<anonymous>:null:null)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:26
    at eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:103:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
.
[10/5/2020, 09:34:36] [eWeLink] [Foyer 2 Way] could not be initialised as TypeError: (this.config.hideMasters || "").includes is not a function
    at eWeLink.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:218:45)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:44
    at Map.forEach (<anonymous>:null:null)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:26
    at eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:103:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
.
[10/5/2020, 09:34:36] [eWeLink]  → [EdwinLed] initialised and found locally with IP [10.1.1.49].
[10/5/2020, 09:34:36] [eWeLink]  → [KaylinLED] initialised and found locally with IP [10.1.1.30].
[10/5/2020, 09:34:36] [eWeLink] [Kitch3way] could not be initialised as TypeError: (this.config.hideMasters || "").includes is not a function
    at eWeLink.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:218:45)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:44
    at Map.forEach (<anonymous>:null:null)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:26
    at eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:103:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
.
[10/5/2020, 09:34:36] [eWeLink] [Liv3way] could not be initialised as TypeError: (this.config.hideMasters || "").includes is not a function
    at eWeLink.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:218:45)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:44
    at Map.forEach (<anonymous>:null:null)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:80:26
    at eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:103:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
.
[10/5/2020, 09:34:36] [eWeLink]  → [KitchLed1] initialised and found locally with IP [10.1.1.35].
[10/5/2020, 09:34:36] [eWeLink]  → [Main bedroom Led] initialised and found locally with IP [10.1.1.25].
[10/5/2020, 09:34:36] [eWeLink] eWeLink sync complete. Don't forget to ⭐️  this plugin on GitHub if you're finding it useful!
[10/5/2020, 09:34:42] [eWeLink] WS message received.
[10/5/2020, 09:34:42] [eWeLink] [device000e64] WS update received and will be refreshed.
[10/5/2020, 09:34:47] [eWeLink] WS message received.
[10/5/2020, 09:34:47] [eWeLink] [device000e64] WS update received and will be refreshed.

[cid:image003.png@01D69AFB.FAFEF510]
