### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by racdamico** [bwp91/homebridge-ewelink#123]
Today my homebridge started to report this error:

```
[10/29/2020, 6:12:08 PM] [eWeLink] WS login failed [Unknown parameters received
{
  "error": 406,
  "apikey": "46255a8d-b932-4ec3-ba26-6bd5ad346503",
  "sequence": "1603991528053",
  "actionName": "userOnline"
}].
```

Any tips on how to solve it. Or maybe ewelink changed something?

homebridge-ewelink v3.9.0

pi@raspberrypi:~$ homebridge -V
1.1.6

**Comment by bwp91** [comment]
This 406 error can sometimes happen if you are using the same ewelink account with two homebridge instances or two different ewelink plugins.
Does this apply to you?

**Comment by racdamico** [comment]
> This 406 error can sometimes happen if you are using the same ewelink account with two homebridge instances or two different ewelink plugins.
> Does this apply to you?

No. Only 1 plugin and I have only 1 homebridge. Just in case I logged out from mobile application but still remain the error

`[10/29/2020, 7:34:13 PM] [eWeLink] WS login failed [Unknown parameters received
{
  "error": 406,
  "apikey": "46255a8d-b932-4ec3-ba26-6bd5ad346503",
  "sequence": "1603996453775",
  "actionName": "userOnline"
}].
`

**Comment by bwp91** [comment]
And do you use the same ewelink credentials between ewelink app and homebridge? or a separate "shared" account?

**Comment by bwp91** [comment]
also, please let me know if you have recently switched from homebridge-ewelink-max to this plugin

**Comment by zkrige** [comment]
I'm seeing the same issue. I migrated from homebridge-ewelink-max to this plugin, but am still seeing messages like this

`WebSocket messge received:  {"error":400,"reason":"Bad Request","apikey":"xxxx","sequence":"xxxx","actionName":"userOnline"}`

**Comment by bwp91** [comment]
Any luck yet?

**Comment by racdamico** [comment]
> And do you use the same ewelink credentials between ewelink app and homebridge? or a separate "shared" account?

sorry for the delay. Yes, same account.

>  also, please let me know if you have recently switched from homebridge-ewelink-max to this plugin

I had an issue with homebridge and reinstalled everything again. Not sure which one I was using before, but my guess it's the same plugin.

**Comment by bwp91** [comment]
Could you restart homebridge and paste the initial homebridge starting logs?
(please check through the logs and remove any personal info (emails, passwords, etc)

**Comment by racdamico** [comment]
Here is the LOG:


```
[10/30/2020, 8:12:15 PM] [Homebridge UI] Homebridge restart request received
[10/30/2020, 8:12:15 PM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[10/30/2020, 8:12:15 PM] [HB Supervisor] Sending SIGTERM to Homebridge
[10/30/2020, 8:12:15 PM] Got SIGTERM, shutting down Homebridge...
[10/30/2020, 8:12:21 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[10/30/2020, 8:12:26 PM] [HB Supervisor] Restarting Homebridge...
[10/30/2020, 8:12:26 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/30/2020, 8:12:26 PM] [HB Supervisor] Started Homebridge v1.1.6 with PID: 1237
[10/30/2020, 8:12:33 PM] Loaded config.json with 2 accessories and 5 platforms.
[10/30/2020, 8:12:33 PM] ---
[10/30/2020, 8:12:40 PM] Loaded plugin: homebridge-config-ui-x@4.31.0
[10/30/2020, 8:12:40 PM] Registering platform 'homebridge-config-ui-x.config'
[10/30/2020, 8:12:40 PM] ---
[10/30/2020, 8:12:57 PM] Loaded plugin: homebridge-ewelink@3.9.0
[10/30/2020, 8:12:57 PM] Registering platform 'homebridge-ewelink.eWeLink'
[10/30/2020, 8:12:57 PM] ---
[10/30/2020, 8:13:01 PM] Loaded plugin: homebridge-mi-led-desk-lamp@1.2.0
[10/30/2020, 8:13:01 PM] Registering accessory 'homebridge-mi-led-desk-lamp.mi-led-desk-lamp'
[10/30/2020, 8:13:01 PM] ---
[10/30/2020, 8:13:04 PM] Loaded plugin: homebridge-samsung-tizen@4.3.3
[10/30/2020, 8:13:04 PM] Registering platform 'homebridge-samsung-tizen.SamsungTizen'
[10/30/2020, 8:13:04 PM] ---
[10/30/2020, 8:13:11 PM] Loaded plugin: homebridge-samsungtv-control@2.0.0
[10/30/2020, 8:13:11 PM] Registering platform 'homebridge-samsungtv-control.SamsungTVControl'
[10/30/2020, 8:13:11 PM] ---
[10/30/2020, 8:13:14 PM] Loaded plugin: homebridge-xiaomi-fan@1.4.3
[10/30/2020, 8:13:14 PM] Registering platform 'homebridge-xiaomi-fan.xiaomifan'
[10/30/2020, 8:13:14 PM] ---
[10/30/2020, 8:13:19 PM] Loaded plugin: homebridge-xiaomi-roborock-vacuum@0.13.5
[10/30/2020, 8:13:19 PM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
[10/30/2020, 8:13:19 PM] ---
[10/30/2020, 8:13:19 PM] Loaded plugin: @milo526/homebridge-tuya-web@0.4.8
[10/30/2020, 8:13:19 PM] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[10/30/2020, 8:13:19 PM] ---
[10/30/2020, 8:13:19 PM] Loading 5 platforms...
[10/30/2020, 8:13:19 PM] [Config] Initializing config platform...
[10/30/2020, 8:13:20 PM] [Config] Running in Service Mode
[10/30/2020, 8:13:20 PM] [xiaomifan] Initializing xiaomifan platform...
[10/30/2020, 8:13:20 PM] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[10/30/2020, 8:13:20 PM] [eWeLink] Initializing eWeLink platform...
[10/30/2020, 8:13:20 PM] [SamsungTVControl] Initializing SamsungTVControl platform...
[10/30/2020, 8:13:20 PM] Loading 2 accessories...
[10/30/2020, 8:13:20 PM] [My desk lamp] Initializing mi-led-desk-lamp accessory...
[10/30/2020, 8:13:20 PM] [My desk lamp] Connect to device
[10/30/2020, 8:13:20 PM] [Xiaomi Mi Robot Vaccum] Initializing XiaomiRoborockVacuum accessory...
HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
[10/30/2020, 8:13:20 PM] [TuyaWebPlatform] Loading accessory from cache: Toma agua
[10/30/2020, 8:13:20 PM] [TuyaWebPlatform] Loading accessory from cache: Lavaropa
[10/30/2020, 8:13:20 PM] [TuyaWebPlatform] Loading accessory from cache: SMART BULB
[10/30/2020, 8:13:20 PM] [TuyaWebPlatform] Loading accessory from cache: Lamp Miguel
[10/30/2020, 8:13:20 PM] [TuyaWebPlatform] Loading accessory from cache: Lavavajilla
[10/30/2020, 8:13:20 PM] [xiaomifan] Init - initializing devices
[10/30/2020, 8:13:20 PM] [xiaomifan] [My Xiaomi Fan] Init - got fan configuration, initializing device with name: My Xiaomi Fan
[10/30/2020, 8:13:20 PM] [xiaomifan] [Fan 1C] Init - got fan configuration, initializing device with name: Fan 1C
[10/30/2020, 8:13:21 PM] [eWeLink] Plugin has finished initialising. Syncing with eWeLink.
Setup Payload:
X-HM://0023ISYWBD
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-xxx │     
    └────────────┘     
                       
[10/30/2020, 8:13:21 PM] Homebridge is running on port 51826.
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] STA getDevice | Connected to: 192.168.XX.XXX
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] STA getDevice | Model: roborock.vacuum.s5
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] STA getDevice | State: charging
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] STA getDevice | FanSpeed: 104
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] STA getDevice | BatteryLevel: 100
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] INF getRoomMap | roborock.vacuum.s5 | Map is 
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] INF getSerialNumber | roborock.vacuum.s5 | Serial Number is R00XXXXXXX00993
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] STA getDevice | Serialnumber: R00XXXXXXXXX0993
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] INF getFirmware | roborock.vacuum.s5 | Firmwareversion is 3.5.7_002008
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] STA getDevice | Firmwareversion: 3.5.7_002008
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] INF changedCleaning | roborock.vacuum.s5 | Cleaning is OFF.
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] MON changedCharging | roborock.vacuum.s5 | ChargingState is now true
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] INF changedCharging | roborock.vacuum.s5 | Charging is active
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] INF changedCharging | roborock.vacuum.s5 | Robot was docked.
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] MON changedSpeed | roborock.vacuum.s5 | FanSpeed is now 104%
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] INF changedSpeed | roborock.vacuum.s5 | Speed was changed to 104% (Max), for HomeKit 100%
[10/30/2020, 8:13:22 PM] [Xiaomi Mi Robot Vaccum] INF changedPause | roborock.vacuum.s5 | Paused not possible, no cleaning
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] Missing required `id` property on device type overwrite, received:
{
  "device_type": "form"
}
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] Existing Accessory found [Name: Toma agua] [Tuya ID: 052XXXXbc93cb7e] [HomeBridge ID: bbdf5eab-x-x-a66c-5bffx75f9]
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [Toma agua] Characteristic.On - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] Existing Accessory found [Name: Lavaropa] [Tuya ID: 8135xa6054] [HomeBridge ID: 6f8e3833-x-x-94b3-639fxcfa13]
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [Lavaropa] Characteristic.On - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] Existing Accessory found [Name: SMART BULB] [Tuya ID: bf17xff1snsy] [HomeBridge ID: cf0af091-x-401f-861a-d47xd28ea]
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [SMART BULB] Characteristic.On - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [SMART BULB] Characteristic.Brightness - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [SMART BULB] Characteristic.ColorTemperature - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [SMART BULB] Characteristic.Hue - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [SMART BULB] Characteristic.Saturation - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] Existing Accessory found [Name: Lamp Miguel] [Tuya ID: bfc35xxaa0aw1js] [HomeBridge ID: db20bd5d-x-x-b6a8-a04ex65286]
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [Lamp Miguel] Characteristic.On - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [Lamp Miguel] Characteristic.Brightness - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [Lamp Miguel] Characteristic.ColorTemperature - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [Lamp Miguel] Characteristic.Hue - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [Lamp Miguel] Characteristic.Saturation - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] Existing Accessory found [Name: Lavavajilla] [Tuya ID: 8135366xx94c9cf08] [HomeBridge ID: 2407c619-x-x-b3ed-aebex2d0a]
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] [Lavavajilla] Characteristic.On - Enabled
[10/30/2020, 8:13:23 PM] [TuyaWebPlatform] Enable cloud polling with interval 605s
[10/30/2020, 8:13:27 PM] [SamsungTVControl] [TV] Samsung 7 Series (55) - Please run npx homebridge-samsungtv-control pair2 192.168.x.x cc:x:x:x:eb:x ornpx homebridge-samsungtv-control pair1 192.168.x.x cc:x:a4:x:x:x to get a pairing token.
[10/30/2020, 8:13:27 PM] [SamsungTVControl] Found device [TV] Samsung 7 Series (55) (UE55NU7105), usn: uuid:d2097685-x-x-833f-674e0x7bf
[10/30/2020, 8:13:28 PM] [TV] Samsung 7 Series (55) is running on port 52100.
[10/30/2020, 8:13:28 PM] Please add [[TV] Samsung 7 Series (55)] manually in Home app. Setup Code: 031-45-xxx
[10/30/2020, 8:13:29 PM] [eWeLink] [1] eWeLink devices loaded from the Homebridge cache.
[10/30/2020, 8:13:29 PM] [eWeLink] [1] primary devices loaded from your eWeLink account.
[10/30/2020, 8:13:29 PM] [eWeLink]  → [Cozinha] initialised and found locally with IP [192.168.x.x].
[10/30/2020, 8:13:29 PM] [eWeLink] eWeLink sync complete. Don't forget to ⭐️  this plugin on GitHub if you're finding it useful!
```

**Comment by bwp91** [comment]
This all looks fine, so i'll need to look into more things.

1. Which device type/model is Cozinha?
2. Could you post from your homebridge config file the ewelink section? (please remove your username and password!)

Thanks

**Comment by racdamico** [comment]
> 1. Which device type/model is Cozinha?
This device: Sonoff Wall switch no netraul
https://www.banggood.com/SONOFF-T4EU1C-WIFI-Wall-Touch-Switch-1-Gang-EU-No-Neutral-Wire-Required-Switches-Smart-Single-Wire-Wall-Switch-Works-With-Alexa-Google-Home-p-1555204.html?cur_warehouse=CN

> 2. Could you post from your homebridge config file the ewelink section? (please remove your username and password!)

```
        {
            "name": "eWeLink",
            "countryCode": "34",
            "username": "blablabla@gmail.com",
            "password": "THANKYOU",
            "debug": false,
            "debugReqRes": false,
            "disableHTTPRefresh": false,
            "disableEveLogging": false,
            "inUsePowerThreshold": 0,
            "hideTHSwitch": false,
            "lowBattThreshold": 25,
            "sensorTimeLength": 2,
            "sensorTimeDifference": 120,
            "hideZBLDPress": false,
            "groups": [
                {
                    "operationTime": 100
                }
            ],
            "bridgeSensors": [
                {
                    "type": "motion"
                }
            ],
            "platform": "eWeLink"
        },
```

Thank you very much for your help

**Comment by bwp91** [comment]
Could we message on the [Homebridge Discord](https://discord.gg/7X36mdw)? My username there is `bwp91`

**Comment by Ricky-Garcia1110** [comment]
I've had the same problem for three days and I don't know what to do to solve it since everything was fine before. I get error 406 and "login websocket request failed error undefined. websocket was close reason 1006"
![C9FBC6DC-EFB4-463D-B1CE-6EA519A75A5B](https://user-images.githubusercontent.com/51188604/97768042-948b6980-1b20-11eb-98ef-6233a806a4df.png)

**Comment by bwp91** [comment]
@Ricky-Garcia1110 which version of the plugin are you using? might be worth updating to see if it helps?

**Comment by bwp91** [comment]
Another suggestion to you both would be to [remove all your eWeLink accessories from the HB cache](https://github.com/bwp91/homebridge-ewelink/wiki/How-to-remove-an-accessory-from-the-cache)

**Comment by Ricky-Garcia1110** [comment]
> @Ricky-Garcia1110 which version of the plugin are you using? might be worth updating to see if it helps?



> @Ricky-Garcia1110 which version of the plugin are you using? might be worth updating to see if it helps?

I have the ewelink max plugin v0.2.1 and I have also tried v3.9.0 but it doesn't run either

**Comment by Ricky-Garcia1110** [comment]
> Another suggestion to you both would be to [remove all your eWeLink accessories from the HB cache](https://github.com/bwp91/homebridge-ewelink/wiki/How-to-remove-an-accessory-from-the-cache)

I just tried to install hb - service but I have hb in docker and I know how to install it there. I hope to solve it because my hk is very sad like this

**Comment by bwp91** [comment]
I can't help if you are using ewelink-max.
But if you try this plugin (homebridge-ewelink) please make sure you have 

* uninstalled ewelink-max
* removed the ewelink-max settings section from the homebridge config
* installed and configured this plugin correctly
* removed the "old" ewelink-max accessories from the cache so that they are readded with this plugin

**Comment by bwp91** [comment]
> Could we message on the [Homebridge Discord](https://discord.gg/7X36mdw)? My username there is `bwp91`

@Ricky-Garcia1110 please also feel free to contact me here and i can take you through some more steps

**Comment by Ricky-Garcia1110** [comment]
> I can't help if you are using ewelink-max.
> But if you try this plugin (homebridge-ewelink) please make sure you have
> 
> * uninstalled ewelink-max
> * removed the ewelink-max settings section from the homebridge config
> * installed and configured this plugin correctly
> * removed the "old" ewelink-max accessories from the cache so that they are readded with this plugin

I have followed your steps but the error that I get now is the following
![2E796E98-A3E6-442A-B0CA-BC6F44D30FD3](https://user-images.githubusercontent.com/51188604/97776248-d212e580-1b66-11eb-839b-fd60aa253d0a.jpeg)

**Comment by bwp91** [comment]
It looks like you don't have any ewelink plugin installed? In the Plugins section is ewelink listed?

**Comment by Ricky-Garcia1110** [comment]
> I can't help if you are using ewelink-max.
> But if you try this plugin (homebridge-ewelink) please make sure you have
> 
> * uninstalled ewelink-max
> * removed the ewelink-max settings section from the homebridge config
> * installed and configured this plugin correctly
> * removed the "old" ewelink-max accessories from the cache so that they are readded with this plugin

I have followed your steps but the error that I get now is the following

> It looks like you don't have any ewelink plugin installed? In the Plugins section is ewelink listed?

yes, I have the homebridge-ewelink plugin v3.9.0

**Comment by bwp91** [comment]
Please can you post here a screenshot of your "installed plugins" page, your full homebridge config (remove usernames, passwords, etc) and a full log of starting Homebridge (ideally copy and pasted text, not screenshots of logs/configs)

**Comment by Ricky-Garcia1110** [comment]
![136E4A3F-E7E5-4404-A371-EAC57BF576AD](https://user-images.githubusercontent.com/51188604/97777455-954bec00-1b70-11eb-8b72-082a1d1f73e6.jpeg)

```
Loaded plugin: homebridge-rpitemp
[10/31/2020, 10:48:14 AM] Registering accessory 'homebridge-rpitemp.RpiTemp'
[10/31/2020, 10:48:14 AM] ---
[10/31/2020, 10:48:14 AM] Loaded plugin: homebridge-config-ui-x
[10/31/2020, 10:48:14 AM] Registering platform 'homebridge-config-ui-x.config'
[10/31/2020, 10:48:14 AM] ---
[10/31/2020, 10:48:14 AM] Loading 1 platforms...
[10/31/2020, 10:48:14 AM] Error: The requested platform 'eWeLink' was not registered by any plugin.
   at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
   at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
   at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
   at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
   at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
   at Module._compile (internal/modules/cjs/loader.js:776:30)
   at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
   at Module.load (internal/modules/cjs/loader.js:653:32)
   at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
   at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[10/31/2020, 10:48:14 AM] Got SIGTERM, shutting down Homebridge...
```

```json
{
   "bridge": {
       "name": "HBEWERPI",
       "username": "CC:22:3D:E3:CE:91",
       "port": 51721,
       "pin": "031-45-155"
   },
   "description": "This is an example configuration file. You can use this as a template for creating your own configuration file containing devices you actually own.",
   "accessories": [
       {
           "accessory": "homebridge-rpitemp.RpiTemp",
           "name": "RPi CPU Temp",
           "tempid": "cpu"
       }
   ],
   "platforms": [
       {
           "name": "eWeLink",
           "countryCode": "34",
           "username": "xxxxxxxx",
           "password": "xxxxxxxx",
           "debug": false,
           "debugReqRes": false,
           "disableHTTPRefresh": false,
           "disableEveLogging": false,
           "inUsePowerThreshold": 0,
           "hideTHSwitch": false,
           "lowBattThreshold": 25,
           "sensorTimeDifference": 120,
           "hideZBLDPress": false,
           "groups": [
               {
                   "operationTime": 100
               }
           ],
           "bridgeSensors": [
               {
                   "sensorTimeLength": 60
               }
           ],
           "platform": "eWeLink"
       }
   ]
}
```
![Uploading 41ED378E-C4D0-4200-99C7-025D875EDA97.jpeg…]()

**Comment by Ricky-Garcia1110** [comment]
I forgot to say that I have the version of hb 0.4.5.3 since node I have it in five containers in docker and I don't know how to update node js that I have it in v 10.16.0

**Comment by bwp91** [comment]
I would suggest updating everything to the latest versions, Homebridge to 1.1.6, node to at v12/v14, and also config-ui-x plugin.

**Comment by Ricky-Garcia1110** [comment]
I have finally managed to solve it by installing hb in terminal and leaving hb in docker for other plugins, ahira if the devices respond, thanks

**Comment by bwp91** [comment]
@Ricky-Garcia1110 glad you somehow got it sorted!

@racdamico any luck yet?

**Comment by racdamico** [comment]
@bwp91 Sorry for my late response. Since the reload of the HB, I didn't have the error on logs anymore. I'm not sure if is that the reason or just a coincidence.

Anyway, I would like to help you if you need more information on this.

Thanks for all your help.

**Comment by bwp91** [comment]
I'm glad it seems like the error has disappeared.
I'm gonna go ahead and close this issue, but do keep an eye on the logs and if you continue getting this error then we can reopen this issue and I will explore further.
Thanks
