### ISSUE TITLE
Error starting Plugin

### ISSUE THREAD

**Issue by iNaiks** [bwp91/homebridge-ewelink#126]
**What issue do you have? Please be as thorough and explicit as possible.**

Hi, I have an issue related with this message when I start the homebridge. 

“[eWeLink]************ cannot load home bridge-ewelink***********
[eWeLink] invalid value “ undefined” for header “host”

I have had eWeLink-Max but I uninstalled before use your plugin

Thanks Nico
...

**Details of your setup.**
Do you use Homebridge or HOOBS?

HomeBridge 
...

Which version of Homebridge/HOOBS do you have?

V1.1.6
...

Which version of this plugin (homebridge-ewelink) do you have?

V3.9.0
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...

**Comment by bwp91** [comment]
Hi Nico,
Please could you turn on "Debug Logging" and "Request & Response Logging" via the plugin settings, restart Homebridge, and copy and paste the logs from Homebridge - the error itself and the lines around it too.
This would be much more helpful to me.
Thanks

**Comment by iNaiks** [comment]
Of corse:
```
************* Cannot load homebridge-ewelink *************
[10/31/2020, 14:04:42] [eWeLink] TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Host"
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:243:14)
    at Object.request (https.js:316:10)
    at RedirectableRequest._performRequest (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/follow-redirects/index.js:241:24)
    at new RedirectableRequest (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/follow-redirects/index.js:60:8)
    at Object.wrappedProtocol.request (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/follow-redirects/index.js:437:14)
    at dispatchHttpRequest (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/axios/lib/adapters/http.js:179:25)
    at new Promise (<anonymous>)
    at httpAdapter (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/axios/lib/adapters/http.js:21:10)
    at dispatchRequest (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/axios/lib/core/dispatchRequest.js:52:10) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
```

This is the configuration (excluded personal info):

```json
{
            "name": "eWeLink",
            "countryCode": "34",
            "username": "##########",
            "password": "##########",
            "debug": true,
            "debugReqRes": true,
            "disableHTTPRefresh": false,
            "disableEveLogging": false,
            "inUsePowerThreshold": 0,
            "hideTHSwitch": false,
            "lowBattThreshold": 25,
            "sensorTimeDifference": 120,
            "hideZBLDPress": false,
            "groups": [
                {
                    "operationTime": 100
                }
            ],
            "bridgeSensors": [
                {
                    "sensorTimeLength": 60
                }
            ],
            "platform": "eWeLink"
        }
```

**Comment by bwp91** [comment]
Could you post the logs from the beginning of restarting Homebridge up to this error?

**Comment by iNaiks** [comment]
```
[HB Supervisor] Restarting Homebridge...
[10/31/2020, 14:04:28] [HB Supervisor] Starting Homebridge with extra flags: -I
[10/31/2020, 14:04:28] [HB Supervisor] Started Homebridge v1.1.6 with PID: 11916
[10/31/2020, 14:04:31] Loaded config.json with 0 accessories and 3 platforms.
[10/31/2020, 14:04:31] ---
[10/31/2020, 14:04:34] Loaded plugin: homebridge-config-ui-x@4.31.0
[10/31/2020, 14:04:34] Registering platform 'homebridge-config-ui-x.config'
[10/31/2020, 14:04:34] ---
[10/31/2020, 14:04:39] Loaded plugin: homebridge-ewelink@3.9.0
[10/31/2020, 14:04:39] Registering platform 'homebridge-ewelink.eWeLink'
[10/31/2020, 14:04:39] ---
[10/31/2020, 14:04:40] Loaded plugin: @milo526/homebridge-tuya-web@0.4.8
[10/31/2020, 14:04:40] Registering platform '@milo526/homebridge-tuya-web.TuyaWebPlatform'
[10/31/2020, 14:04:40] ---
[10/31/2020, 14:04:40] Loading 3 platforms...
[10/31/2020, 14:04:40] [Config] Initializing config platform...
[10/31/2020, 14:04:40] [Config] Running in Service Mode
[10/31/2020, 14:04:40] [TuyaWebPlatform] Initializing TuyaWebPlatform platform...
[10/31/2020, 14:04:40] [eWeLink] Initializing eWeLink platform...
[10/31/2020, 14:04:40] [TuyaWebPlatform] Loading accessory from cache: Cartel APP
[10/31/2020, 14:04:40] [eWeLink] Plugin has finished initialising. Syncing with eWeLink.
[10/31/2020, 14:04:40] [eWeLink] Sending HTTP getHost() request. This text is yellow for clarity.
{
  "appid": "oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq",
  "country_code": "+34",
  "nonce": "0fmaqr6a",
  "ts": 1604149480,
  "version": 8
}
Setup Payload:
X-HM://0023SWMMJ9B5D
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
 
#################
                       
[10/31/2020, 14:04:40] Homebridge is running on port 51284.
[10/31/2020, 14:04:40] [TuyaWebPlatform] Missing required `id` property on device type overwrite, received:
{
  "device_type": "form"
}
[10/31/2020, 14:04:40] [TuyaWebPlatform] [Cartel APP] Characteristic.On - Enabled
[10/31/2020, 14:04:40] [TuyaWebPlatform] Enable cloud polling with interval 605s
[10/31/2020, 14:04:42] [eWeLink] Sending HTTP login() request. This text is yellow for clarity.
{
  "countryCode": "+34",
  "password": "**hidden**",
  "email": "**hidden**"
}

[10/31/2020, 14:04:42] [eWeLink] ************* Cannot load homebridge-ewelink *************
[10/31/2020, 14:04:42] [eWeLink] TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Host"
    at ClientRequest.setHeader (_http_outgoing.js:529:3)
    at new ClientRequest (_http_client.js:243:14)
    at Object.request (https.js:316:10)
    at RedirectableRequest._performRequest (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/follow-redirects/index.js:241:24)
    at new RedirectableRequest (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/follow-redirects/index.js:60:8)
    at Object.wrappedProtocol.request (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/follow-redirects/index.js:437:14)
    at dispatchHttpRequest (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/axios/lib/adapters/http.js:179:25)
    at new Promise (<anonymous>)
    at httpAdapter (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/axios/lib/adapters/http.js:21:10)
    at dispatchRequest (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/axios/lib/core/dispatchRequest.js:52:10) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
```

**Comment by bwp91** [comment]
For some reason you aren't being provided with a http host. I will have to dig a bit deeper, could I message you on the [Homebridge Discord](https://discord.gg/7X36mdw)? My username there is `bwp91`

**Comment by iNaiks** [comment]
Ok I’m in.

**Comment by iNaiks** [comment]
I need to post something?

**Comment by bwp91** [comment]
I’ve already sent you a direct message on there!

**Comment by bwp91** [comment]
Closing this issue now as @iNaiks it is working for you now?

**Comment by iNaiks** [comment]
I think yes. I will test in the next days
