### ISSUE TITLE
Cannot handle Sonoff 4CHPROr3 device

### ISSUE THREAD

**Issue by jovator-git** [bwp91/homebridge-ewelink#128]
I'm trying to configure a Sonoff 4CHPROr3 device.
In the ewelink app, I can add and manage the device without any issue.
As soon as I add the device in ewelink, my homebridge detect the new device but he cannot manage it.
If I reststarted my homebridge ... and can see this message in the logs:

[11/1/2020, 11:42:58] [eWeLink] Initializing eWeLink platform...
[11/1/2020, 11:42:58] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 604edcd2-ebe3-4642-b673-9d13cc0aaf3e
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:416:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:310:19
    at Array.filter (<anonymous>)
    at Server.restoreCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:270:69)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:10)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
...

**Details of your setup.**
Do you use Homebridge or HOOBS?
I use Homebrige latest version, 1.1.6
...

Which version of Homebridge/HOOBS do you have?
version 1.1.6
...

Which version of this plugin (homebridge-ewelink) do you have?
homebridge-ewelink v3.9.0
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...

**Comment by bwp91** [comment]
Hi @jovator-git 
Have you recently moved from `homebridge-ewelink-max`?

**Comment by jovator-git** [comment]
Hi Ben,

No i’ve never used this plugin...
My homebridge config is quite basic, standar homebridge image + ewelink plugin just it.

I should have a look this other plugin?

Thanks!

**Comment by bwp91** [comment]
No, stay with this plugin. 

Please could you remove all accessories from the homebridge cache, and then copy and paste **all** the logs from when homebridge restarts?

**Comment by jovator-git** [comment]
Indeed I’ve done it, the logs I’ve sent to you is just to remove the cache :-(

**Comment by jovator-git** [comment]
Hi Ben,

I've done it once again, and I don't know why, actually It is working :-)
Sorry for this misunderstanding and thank you for your support!

thanks
Jose

**Comment by bwp91** [comment]
Awesome. Glad it's working for you :)
