### ISSUE TITLE
Cannot read property 'httpHost' of undefined

### ISSUE THREAD

**Issue by bartgabriels** [bwp91/homebridge-ewelink#132]
Receiving this error:
[03/11/2020, 19:56:56] [eWeLink] *** Disabling plugin [v3.10.0] ***
[03/11/2020, 19:56:56] [eWeLink] Cannot read property 'httpHost' of undefined

I just changed from Ewelink-Max to Ewelink because of other issues. Worked good for a few days, but now run into this issue.

[03/11/2020, 20:00:16] [eWeLink] Plugin [v3.10.0] initialised. Syncing with eWeLink...
[03/11/2020, 20:00:16] [eWeLink] Sending HTTP getHost() request. This text is yellow for clarity.
{
  "appid": "oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq",
  "country_code": "+32",
  "nonce": "jsf8rc91",
  "ts": 1604430016,
  "version": 8
}

[eWeLink] Sending HTTP login() request. This text is yellow for clarity.
{
  "countryCode": "+32",
  "password": "**hidden**",
  "email": "**hidden**"
}

[eWeLink] Sending HTTP login() request. This text is yellow for clarity.
{
  "countryCode": "+32",
  "password": "**hidden**",
  "email": "**hidden**"
}

[eWeLink] *** Disabling plugin [v3.10.0] ***
[03/11/2020, 20:00:22] [eWeLink] TypeError: Cannot read property 'httpHost' of undefined
    at new eWeLinkWS (/usr/local/lib/node_modules/homebridge-ewelink/lib/ewelink-ws.js:15:25)
    at eWeLinkPlatform.eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/ewelink-platform.js:79:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by bartgabriels** [comment]
Double
