### ISSUE TITLE
 Cannot read property 'httpHost' of undefined

### ISSUE THREAD

**Issue by bartgabriels** [bwp91/homebridge-ewelink#133]
Receiving this error:
[03/11/2020, 19:56:56] [eWeLink] *** Disabling plugin [v3.10.0] ***
[03/11/2020, 19:56:56] [eWeLink] Cannot read property 'httpHost' of undefined

I just changed from Ewelink-Max to Ewelink because of other issues. Worked good for a few days, but now run into this issue.

[03/11/2020, 20:00:16] [eWeLink] Plugin [v3.10.0] initialised. Syncing with eWeLink...
[03/11/2020, 20:00:16] [eWeLink] Sending HTTP getHost() request. This text is yellow for clarity.
{
  "appid": "oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq",
  "country_code": "+32",
  "nonce": "jsf8rc91",
  "ts": 1604430016,
  "version": 8
}

[eWeLink] Sending HTTP login() request. This text is yellow for clarity.
{
  "countryCode": "+32",
  "password": "**hidden**",
  "email": "**hidden**"
}

[eWeLink] Sending HTTP login() request. This text is yellow for clarity.
{
  "countryCode": "+32",
  "password": "**hidden**",
  "email": "**hidden**"
}

[eWeLink] *** Disabling plugin [v3.10.0] ***
[03/11/2020, 20:00:22] [eWeLink] TypeError: Cannot read property 'httpHost' of undefined
    at new eWeLinkWS (/usr/local/lib/node_modules/homebridge-ewelink/lib/ewelink-ws.js:15:25)
    at eWeLinkPlatform.eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/ewelink-platform.js:79:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by bwp91** [comment]
Hi,
Please can I get you to update to a beta version using the "Install Previous Version" feature of the Homebridge UI? And update to `v3.11.0-2`?

<img width="600" alt="Screenshot 2020-11-03 at 19 12 33" src="https://user-images.githubusercontent.com/43026681/98030353-cc3c2f00-1e08-11eb-95a0-3804562663d4.png">

This most likely won't fix the error you are getting, but, will hopefully provide a more specific error message as to why this is happening.

Thanks

**Comment by bartgabriels** [comment]
[03/11/2020, 20:17:33] ---
[03/11/2020, 20:17:34] Loaded plugin: homebridge-ewelink@3.11.0-2
[03/11/2020, 20:17:34] Registering platform 'homebridge-ewelink.eWeLink'
[03/11/2020, 20:17:34] ---

[03/11/2020, 20:17:45] [eWeLink] Plugin [v3.11.0-2] initialised. Syncing with eWeLink...
[03/11/2020, 20:17:45] [eWeLink] Sending HTTP getHost() request. This text is yellow for clarity.
{
  "appid": "oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq",
  "country_code": "+32",
  "nonce": "y8xnciko",
  "ts": 1604431065,
  "version": 8
}

[03/11/2020, 20:17:46] [eWeLink] HTTP API host received [eu-apia.coolkit.cc].
[03/11/2020, 20:17:46] [eWeLink] Sending HTTP login() request. This text is yellow for clarity.
{
  "countryCode": "+32",
  "password": "**hidden**",
  "email": "**hidden**"
}

[03/11/2020, 20:17:48] [eWeLink] New HTTP API host received [us-apia.coolkit.cc].
[03/11/2020, 20:17:48] [eWeLink] Sending HTTP login() request. This text is yellow for clarity.
{
  "countryCode": "+32",
  "password": "**hidden**",
  "email": "**hidden**"
}

[03/11/2020, 20:17:51] [eWeLink] *** Disabling plugin [v3.11.0-2] ***
[03/11/2020, 20:17:51] [eWeLink] TypeError: Cannot read property 'httpHost' of undefined
    at new eWeLinkWS (/usr/local/lib/node_modules/homebridge-ewelink/lib/ewelink-ws.js:15:25)
    at eWeLinkPlatform.eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/ewelink-platform.js:78:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by bwp91** [comment]
Are you using a separate "shared" ewelink account for homebridge or your main ewelink account credentials?

**Comment by bartgabriels** [comment]
Main account. Haven't logged in to the Ewelink app in months.

**Comment by bwp91** [comment]
Could I get you to try updating to `v3.11.0-3`?

**Comment by bartgabriels** [comment]
Works !! Thanks

**Comment by bwp91** [comment]
@bartgabriels one thing I should have mentioned about this version is that any light switch devices you might have, for example TX-1C, TX-2C, etc, will now be exposed in HomeKit as switches rather than lights.

You can use the Home app to show them as lights again, but, mainly I say this because you will need to reconfigure any HomeKit automations that you might have had that involve these devices. If you have them!
