### ISSUE TITLE
Sonoff TH10 Bug after Update

### ISSUE THREAD

**Issue by KKliemann** [bwp91/homebridge-ewelink#177]
after the Update the Sonoff TH10 Temperature-Sensor don't connect to my Homebridge anymore. Homebridge give this Error:

could not be initialised as TypeError: Cannot read property 'context' of undefined
    at new deviceTHOutlet (/usr/local/lib/node_modules/homebridge-ewelink/lib/device/th-outlet.js:12:104)
    at eWeLinkPlatform.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:307:13)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:103:47
    at Map.forEach (<anonymous>)
    at eWeLinkPlatform.eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:103:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5). 

I use Homebridge with config-ui in the latest Version (v1.1.7) 

I have just updated my Eveline-PlugIn to Version 4.0.0, after that Update the Issue is accuered.

Sonoff TH10

I only have one Account @ EweLink

could not be initialised as TypeError: Cannot read property 'context' of undefined
    at new deviceTHOutlet (/usr/local/lib/node_modules/homebridge-ewelink/lib/device/th-outlet.js:12:104)
    at eWeLinkPlatform.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:307:13)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:103:47
    at Map.forEach (<anonymous>)
    at eWeLinkPlatform.eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:103:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5).

**Comment by bwp91** [comment]
Hi what issue are you having? Your initial post is a blank template :)

**Comment by KKliemann** [comment]
Sorry, Now its there! My browser send it blank over night.

**Comment by bwp91** [comment]
Please try v4.0.1 which I have just released

**Comment by KKliemann** [comment]
Thanks, that is better 🙃
Now it’s generally initialised.
„LAN mode is unavailable as not supported“

I think is ok, because the TH10 only support WiFi

**Comment by bwp91** [comment]
Great. Yes the TH10/16 devices don't support LAN mode, so this message is expected.
Thanks for pointing this bug out!
