### ISSUE TITLE
Sonoff RF Bridge error message

### ISSUE THREAD

**Issue by axelweichert** [bwp91/homebridge-ewelink#185]
### What issue do you have? Please be as thorough and explicit as possible.

[Sonof RF Bridge 3] could not be initialised as val.charAt is not a function.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

Homebridge Config-UI

* Which version of Homebridge/HOOBS do you have?

1.1.7

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

14.15.4

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

4.4.1

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff RF Bridge Rev. 1 and Rev. 2

### Please paste any relevant logs below.

[Sonof RF Bridge 3] could not be initialised as val.charAt is not a function.
```

```

**Comment by bwp91** [comment]
Hi @axelweichert 
Please can you turn on Debug Logging via the plugin settings and restart Homebridge? This should give a full length error message in the logs which I would be grateful to see.
Thanks

**Comment by axelweichert** [comment]
[20/01/2021, 15:16:22] [eWeLink] [Sonof RF Bridge 3] could not be initialised as TypeError: val.charAt is not a function
    at ucfirst (/usr/local/lib/node_modules/homebridge-ewelink/lib/fakegato/fakegato-history.js:64:16)
    at FakeGatoHistory.registerEvents (/usr/local/lib/node_modules/homebridge-ewelink/lib/fakegato/fakegato-history.js:433:75)
    at new FakeGatoHistory (/usr/local/lib/node_modules/homebridge-ewelink/lib/fakegato/fakegato-history.js:373:12)
    at new deviceRFBridge (/usr/local/lib/node_modules/homebridge-ewelink/lib/device/rf-bridge.js:83:34)
    at eWeLinkPlatform.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:444:29)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:107:47
    at Map.forEach (<anonymous>)
    at eWeLinkPlatform.eWeLinkSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:107:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5).

**Comment by bwp91** [comment]
Thanks. Please update to v4.4.2.

It might be an idea to remove this RF bridge from the cache so it is re-added properly with its subdevices.

There was an issue with the code when it added subdevices of RF bridges, which has been fixed, but might need to be re-added to work again.

Please let me know how you get on

**Comment by axelweichert** [comment]
Perfect. Everything works fine now. Thanks for your help. :-)
