### ISSUE TITLE
Sonoff Zigbee Motion Sensor SNZB-03

### ISSUE THREAD

**Issue by ojoaosemtil** [bwp91/homebridge-ewelink#203]
### What issue do you have? Please be as thorough and explicit as possible.

While using the motion sensor, sometimes it gets stuck on “motion detected”. At first I thought it was a problem with the device or the eWeLink app, but when I restart homebridge, the sensor stays in no motion detected until I wave in front off it, it then flashes the red light but doesn’t trigger any automation, and the movement is not logged in the eWeLink app.
But after a while, and one or two attempts, everything starts working as expected.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

I use homebridge+config-ui

* Which version of Homebridge/HOOBS do you have?

I have homebridge 1.3.1, but it happened in previous versions.

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

I run homebridge in a Raspberry Pi, Node.js version 14.15.5 and NPM 7.5.4

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

I have version 4.7.6, it happened on previous versions.

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

I have some zigbee temperature and WiFi door sensors working with no problems, theming issue is with zigbee motion sensor SNZB-03

### Please paste any relevant logs below.

no relevant logs as I’m aware.

**Comment by bwp91** [comment]
Hi @ojoaosemtil 

The device sends its current status to eWeLink and eWeLink sends this information onto the plugin. The plugin doesn't and cannot create log entries for motion detected in the eWeLink app.

When motion is detected, ewelink sends a notification to the plugin which in turns sets the state of the HomeKit motion sensor. Then after 60 seconds of no further motion detected by the device, ewelink will send a notification to the plugin and the plugin will update the HomeKit motion sensor with no motion detected.

In short, the plugin completely relies on updates from ewelink for both 'motion detected' and 'no motion detected' notifications. (which is different for e.g. rf bridge motion sensors where the plugin will automatically set the sensor back to 'no motion detected' after X seconds).

> sometimes it gets stuck on “motion detected”

Either:

* If the sensor detects motion then it starts checking for a period of 60 seconds of no motion. If, say, the sensor detects motion 40 seconds after the first detection, then this 60 seconds will reset. The HomeKit motion sensor will say 'motion detected' during this entire time.

* The plugin is not receiving the notification from eWeLink that no motion has been detected for 60 seconds.

You are correct in that, currently, if you restart Homebridge, all motion sensors will be reset to 'no motion detected'. This is in case ewelink sends a 'no motion detected' notification whilst Homebridge is restarting, in this case the notification will not be registered by the plugin and the HomeKit sensor will indefinitely say 'motion detected'.

I hope I have answered your question with the above info?

Thanks

**Comment by ojoaosemtil** [comment]
Oh thank you so much for the explanation!

So the problem is the eWeLink server, it makes sense...

I have a firmware update available in the zigbee bridge, but everytime I try, it fails to update at 90%.

I know it has nothing to do with your plugin but I thought maybe you’re aware of this and have any work around...

Thanks in advance, and thank you for you work!

**Comment by bwp91** [comment]
Do you use your main ewelink credentials for the plugin?

**Comment by ojoaosemtil** [comment]
Yes, email and password are the same as the ewelink app

**Comment by bwp91** [comment]
That's okay, I was just going to say if you use a secondary account (like some people do) sometimes (not a lot) notifications can get missed.

**Comment by ojoaosemtil** [comment]
No, that’s not the case..but I’m searching online and started to figure that many people has some sort of issues with this motion sensor and the bridge firmware updates.

**Comment by ojoaosemtil** [comment]
I found this in the homebridge logs:

```
[23/02/2021, 18:31:53] [eWeLink] [Sensor Closet] initialised and LAN mode unavailable as not supported.
[23/02/2021, 18:31:53] [eWeLink] [Sensor Office] initialised and LAN mode unavailable as not supported.
[23/02/2021, 18:31:53] [homebridge-ewelink] This plugin generated a warning from the characteristic 'Motion Detected': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[23/02/2021, 18:31:53] [eWeLink] [Sensor Cozinha] initialised and LAN mode unavailable as not supported.
[23/02/2021, 18:31:53] [eWeLink] [Janela Sala] initialised and LAN mode unavailable as not supported.
[23/02/2021, 18:31:53] [eWeLink] [Porta Escritório] initialised and LAN mode unavailable as not supported.
[23/02/2021, 18:31:53] [homebridge-ewelink] This plugin generated a warning from the characteristic 'Last Activation': characteristic was expected valid number and received NaN. See https://git.io/JtMGR for more info.
[23/02/2021, 18:31:53] [eWeLink] [Porta Quarto] initialised and LAN mode unavailable as not supported.
[23/02/2021, 18:31:53] [eWeLink] ✓ Setup complete. Have a feature request? Visit http://bit.ly/hb-ewelink-issues to ask!
```

“Sensor Cozinha” is the motion sensor.
This appears everytime homebridge restarts

**Comment by bwp91** [comment]
Could you run Homebridge in DEBUG mode (not the plugin setting for debug but the main homebridge debug option)

and post the logs that that generates?

**Comment by ojoaosemtil** [comment]
Sure, here it is ("Sensor Cozinha" is the motion sensor):

```
[23/02/2021, 19:01:52] [eWeLink] [Sensor Closet] initialised and LAN mode unavailable as not supported.
[23/02/2021, 19:01:52] [eWeLink] [Sensor Office] initialised and LAN mode unavailable as not supported.
[23/02/2021, 19:01:52] [homebridge-ewelink] This plugin generated a warning from the characteristic 'Motion Detected': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[23/02/2021, 19:01:52] [homebridge-ewelink] Error: 
    at MotionDetected.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2164:105)
    at MotionDetected.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at MotionDetected.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1365:20)
    at MotionSensor.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:465:35)
    at deviceZBSensorMotion.externalUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/device/zigbee/sensor-motion.js:67:22)
    at eWeLinkPlatform.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:1093:27)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:437:47
    at Map.forEach (<anonymous>)
    at eWeLinkPlatform.pluginSetup (/usr/local/lib/node_modules/homebridge-ewelink/lib/index.js:437:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[23/02/2021, 19:01:52] [eWeLink] [Sensor Cozinha] initialised and LAN mode unavailable as not supported.
[23/02/2021, 19:01:52] [eWeLink] [Janela Sala] initialised and LAN mode unavailable as not supported.
[23/02/2021, 19:01:52] [eWeLink] [Porta Escritório] initialised and LAN mode unavailable as not supported.
[23/02/2021, 19:01:53] [eWeLink] [Porta Quarto] initialised and LAN mode unavailable as not supported.
[23/02/2021, 19:01:53] [eWeLink] ✓ Setup complete. Thanks for using this plugin, I hope you find it helpful!
```

**Comment by bwp91** [comment]
Could I message you on Discord?
https://discord.gg/cMGhNtZ3tW

**Comment by ojoaosemtil** [comment]
Ok I accepted your invite!
