### ISSUE TITLE
Plugin won't initialise 

### ISSUE THREAD

**Issue by The-Doddler** [bwp91/homebridge-ewelink#214]
### What issue do you have? Please be as thorough and explicit as possible.

Plugin won't intilise 

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

Homebridge and config-ui

* Which version of Homebridge/HOOBS do you have?

Homebridge v 1.3.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

Node.js Version | v14.16.0
NPM v6.14.11

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

Version 5.1.1

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

All devices do not work

### Please paste any relevant logs below.

```
[3/5/2021, 9:24:56 AM] ---
[3/5/2021, 9:24:57 AM] Loaded plugin: homebridge-config-ui-x@4.39.1
[3/5/2021, 9:24:57 AM] Registering platform 'homebridge-config-ui-x.config'
[3/5/2021, 9:24:57 AM] ---
[3/5/2021, 9:24:57 AM] Loaded plugin: homebridge-envisalink@0.2.16
[3/5/2021, 9:24:57 AM] Registering platform 'homebridge-envisalink.Envisalink'
[3/5/2021, 9:24:57 AM] ---[3/5/2021, 9:24:57 AM] Loaded plugin: homebridge-ewelink@5.1.1
[3/5/2021, 9:24:57 AM] Registering platform 'homebridge-ewelink.eWeLink'
[3/5/2021, 9:24:57 AM] ---
[3/5/2021, 9:24:57 AM] Loading 2 platforms...
[3/5/2021, 9:24:57 AM] [Config] Initializing config platform...
[3/5/2021, 9:24:57 AM] [Config] Running in Service Mode
[3/5/2021, 9:24:57 AM] [eWeLink] Initializing eWeLink platform...
[3/5/2021, 9:24:57 AM] [eWeLink] [v5.1.1] initialised. Syncing with eWeLink.
[3/5/2021, 9:24:57 AM] [eWeLink] ***** Disabling plugin [v5.1.1]. *****
[3/5/2021, 9:24:57 AM] [eWeLink] ***** Invalid or unexpected tokenyE s`d�����. *****
```

**Comment by bwp91** [comment]
Hi, please could you post your config for ewelink? 
Please redact your username and password!

**Comment by The-Doddler** [comment]
{
    "name": "eWeLink",
    "countryCode": "27",
    "username": "",
    "password": "",
    "mode": "auto",
    "platform": "eWeLink"

**Comment by bwp91** [comment]
Ah pretty standard then 😅
Do you get this error every time you restart Homebridge?

**Comment by The-Doddler** [comment]
Yeah I'm a rookie!

Homebridge crashed, I unisntalled and did a reinstall. Now homebridge works, but I can't get the ewelink pluginn to load.

Yes it is everytime it restarts.

Thanks

**Comment by bwp91** [comment]
Never seen this message before so will need some more info from you, can I message you on discord?

https://discord.gg/cMGhNtZ3tW

**Comment by The-Doddler** [comment]
Here is the detailed log:

[3/5/2021, 12:29:00 PM] Loading 2 platforms...
[3/5/2021, 12:29:00 PM] [Config] Initializing config platform...
[3/5/2021, 12:29:00 PM] [Config] Running in Service Mode
[3/5/2021, 12:29:00 PM] [eWeLink] Initializing eWeLink platform...
[3/5/2021, 12:29:00 PM] [eWeLink] [v5.1.2-3] initialised. Syncing with eWeLink.
[3/5/2021, 12:29:00 PM] [eWeLink] ***** Disabling plugin [v5.1.2-3]. *****
[3/5/2021, 12:29:00 PM] [eWeLink] ***** /usr/lib/node_modules/homebridge-ewelink/node_modules/axios/lib/cancel/CancelToken.js:1
yE s`d�����
 ^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-ewelink/node_modules/axios/lib/axios.js:41:21)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10). *****
