### ISSUE TITLE
Error keeps popping up on logs

### ISSUE THREAD

**Issue by DarkSyler21** [bwp91/homebridge-ewelink#231]
### What issue do you have? Please be as thorough and explicit as possible.

Same error keeps popping up in the logs regardless of try using product connected to ewelink

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

Homebridge UI 4.41

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Homebridge on RPI4
Node 14.16.0
NPM 6.14.11

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

5.6

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

using both iFan03 and sonoff L1 led strip

### Please paste any relevant logs below.

```
06/04/2021, 02:58:40] [eWeLink] WS could not be opened and will try again in 5 seconds: WebSocket closed with reason: undefined (undefined). at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/index.js:407:19).
[06/04/2021, 02:58:47] [eWeLink] WS login failed as Can't send data because WebSocket is not opened. at exports.throwIf (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/utils.js:4:11).
[06/04/2021, 03:01:34] [eWeLink] WS could not be opened and will try again in 5 seconds: WebSocket closed with reason: undefined (undefined). at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/index.js:407:19).
[06/04/2021, 03:01:40] [eWeLink] WS could not be opened and will try again in 5 seconds: WebSocket closed with reason: undefined (undefined). at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/index.js:407:19).
[06/04/2021, 03:01:42] [eWeLink] WS login failed as Can't send data because WebSocket is not opened. at exports.throwIf (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/utils.js:4:11).
[06/04/2021, 03:58:41] [eWeLink] WS could not be opened and will try again in 5 seconds: WebSocket closed with reason: undefined (undefined). at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/index.js:407:19).
[06/04/2021, 03:58:48] [eWeLink] WS could not be opened and will try again in 5 seconds: WebSocket closed with reason: undefined (undefined). at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/index.js:407:19).
[06/04/2021, 03:58:49] [eWeLink] WS login failed as Can't send data because WebSocket is not opened. at exports.throwIf (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/utils.js:4:11).
[06/04/2021, 03:58:49] [eWeLink] WS login failed as Can't send data because WebSocket is not opened. at exports.throwIf (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/utils.js:4:11).
[06/04/2021, 04:01:36] [eWeLink] WS could not be opened and will try again in 5 seconds: WebSocket closed with reason: undefined (undefined). at WebSocketAsPromised._handleClose (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/index.js:407:19).
```

**Comment by bwp91** [comment]
Hi, are you based in Asia by any chance? I mean, is your ewelink account based in the Asia continent?

**Comment by DarkSyler21** [comment]
> Hi, are you based in Asia by any chance? I mean, is your ewelink account based in the Asia continent?

don't see anything on the app to check. when registered I registered in region (972) so I don't think the account based in Asia

**Comment by bwp91** [comment]
Can you restart Homebridge to see if anything has resolved? There have been a number of users based in Asia experiencing problems with one of the ewelink servers.

I have been testing over the last few days and ironically it seems to have started to work again this afternoon.

If this doesnt work then could you update to the beta version of the plugin? And also turn on debug logging in the plugin settings.

**Comment by DarkSyler21** [comment]
> Can you restart Homebridge to see if anything has resolved? There have been a number of users based in Asia experiencing problems with one of the ewelink servers.
> 
> I have been testing over the last few days and ironically it seems to have started to work again this afternoon.
> 
> If this doesnt work then could you update to the beta version of the plugin? And also turn on debug logging in the plugin settings.

Yeah lol restarted not long after you wrote the comment and until now a night later I don't see any error from the plugin.
weird even though as I said it worked flawlessly the entire time just those errors appearing for a week now.
Thanks for the assist :)

**Comment by bwp91** [comment]
Ah good to hear no more errors. It was a ewelink server problem that had been troubling me for a few days. seemed to have fixed just coincidentally as you posted the issue!
