### ISSUE TITLE
Obstruction Detect not working did something change?

### ISSUE THREAD

**Issue by MoTechnicalities** [bwp91/homebridge-ewelink#250]
### What issue do you have? Please be as thorough and explicit as possible.

Obstruction Detect not working

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

    **(1) Homebridge (+ config-ui)**

* Which version of Homebridge/HOOBS do you have?

   **v1.3.4**

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

   Raspberry Pi
   Node.js Version v14.16.1
   Npm Version v7.12.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

   homebridge-ewelink v6.5.0
   Not sure when the issue started, but just noticed it.

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

  Two Eachen GD-DC5 devices, each paired with a Sonoff MINI R2 for Obstruct Detection

### Please paste any relevant logs below.

```
[06/05/2021, 18:02:37] [eWeLink] [Garage Door 1] initialising with options {"disableDeviceLogging":false,"operationTime":120,"type":"garage_eachen"}.
[06/05/2021, 18:02:37] [eWeLink] [Garage Door 1] initialised and found locally with IP [192.168.x.xxx].
[06/05/2021, 18:02:37] [eWeLink] [Garage Door 2] initialising with options {"disableDeviceLogging":false,"operationTime":120,"type":"garage_eachen"}.
[06/05/2021, 18:02:38] [eWeLink] [Garage Door 2] initialised and found locally with IP [192.168.x.xx].
[06/05/2021, 18:02:38] [eWeLink] [Obstruct1] could not be initialised as Cannot read property 'get' of undefined at new deviceGarageODSwitch (/usr/local/lib/node_modules/homebridge-ewelink/lib/device/simulation/garage-od-switch.js:22:40).
[06/05/2021, 18:02:38] [eWeLink] [Obstruct2] could not be initialised as Cannot read property 'get' of undefined at new deviceGarageODSwitch (/usr/local/lib/node_modules/homebridge-ewelink/lib/device/simulation/garage-od-switch.js:22:40).
[06/05/2021, 18:02:38] [eWeLink] ✓ Setup complete. Want to see this plugin in your own language? Let me know!
```

**Comment by bwp91** [comment]
Hi @MoTechnicalities 

Please try v6.5.1 and let me know if this issue is solved!

Thanks

**Comment by MoTechnicalities** [comment]
> Please try v6.5.1 and let me know if this issue is solved!
> 
> Thanks

I have confirmed that v6.5.1 has resolved this issue. Obstruction Detection is now working. Thank you!
