### ISSUE TITLE
Garage simulation doesn't work 

### ISSUE THREAD

**Issue by xnonim** [bwp91/homebridge-ewelink#251]
### What issue do you have? Please be as thorough and explicit as possible.

im simulating a garage door with a RE5V1C Sonoof as single channel, In home app, it appears as "incompatible"

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

homebridge + config-ui

* Which version of Homebridge/HOOBS do you have?

homebridge 1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Ubuntu 20.04
node.js v 14.16.1

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

i don't remember from what version it stopped working, but it was working
I tried to downgrade the version of plugin, without succesfull and same logs

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

simulating garage door RE5V1C
close/open sensor dw2

ps: I verified it worked properly in ewe link app, both of them
I use the "owner' account in homebridge

i forgot to mention, in "my devices" tab, it says is offline, lan and cloud mode, and doesn't find the local ip, but as I said, it worked correctly in ewe link app

### Please paste any relevant logs below.

[5/7/2021, 12:15:02 PM] [eWeLink] [Porton ] could not be initialised as Cannot read property 'context' of undefined at new deviceGarageOne (/usr/lib/node_modules/homebridge-ewelink/lib/device/simulation/garage-one.js:53:30).

```

```

**Comment by bwp91** [comment]
Hi @xnonim 
Are you getting this error message on the latest version of the plugin, v6.5.1?
Thanks

**Comment by xnonim** [comment]
Hi @bwp91 yes, and I tried to downgrade version per version down, and everyone says the same.
but as I said before, some time ago it was working flawlessly

**Comment by bwp91** [comment]
> i forgot to mention, in "my devices" tab, it says is offline, lan and cloud mode, and doesn't find the local ip, but as I said, it worked correctly in ewe link app

which device are you talking about? The RE5V1C or the DW2?

Can you post full initialisation logs from the ewelink plugin when restarting homebridge?

**Comment by xnonim** [comment]
Hi, I'm talking about the RE5V1C, it shows as offline, and it can't find it in lan mode neither.

These 2 days I'm having problem with my internet connection, tomorrow is coming a technician to fix it, that's why I'm not sending you the logs yet, but when the problem is fixed, I'll send you
Thanks in advance

**Comment by xnonim** [comment]
ok, here's the full log after restarting homebridge, hope it helps

```
[5/10/2021, 5:08:20 PM] [eWeLink] New HTTP API host received [us-apia.coolkit.cc].
[5/10/2021, 5:08:20 PM] [eWeLink] Sending HTTP login() request.
[5/10/2021, 5:08:24 PM] [eWeLink] Web socket host received [us-pconnect4.coolkit.cc].
[5/10/2021, 5:08:25 PM] [eWeLink] LAN discovery starting.
[5/10/2021, 5:08:25 PM] [eWeLink] Sending WS login request.
[5/10/2021, 5:08:25 PM] [eWeLink] WS login successful.
[5/10/2021, 5:08:28 PM] [eWeLink] LAN discovery complete.
[5/10/2021, 5:08:28 PM] [eWeLink] LAN monitoring started.
[5/10/2021, 5:08:28 PM] [eWeLink] [Luz sala] initialising with options {"disableDeviceLogging":false}.
[5/10/2021, 5:08:28 PM] [eWeLink] [Luz sala] initialised and LAN mode unavailable as unreachable.
[5/10/2021, 5:08:28 PM] [eWeLink] [Luz niñas] initialising with options {"disableDeviceLogging":false}.
[5/10/2021, 5:08:28 PM] [eWeLink] [Luz niñas] initialised and LAN mode unavailable as unreachable.
[5/10/2021, 5:08:28 PM] [eWeLink] [Luz baño] initialising with options {"disableDeviceLogging":false}.
[5/10/2021, 5:08:28 PM] [eWeLink] [Luz baño] initialised and LAN mode unavailable as unreachable.
[5/10/2021, 5:08:28 PM] [eWeLink] [Luz cocina] initialising with options {"disableDeviceLogging":false}.
[5/10/2021, 5:08:28 PM] [eWeLink] [Luz cocina] initialised and LAN mode unavailable as unreachable.
**[5/10/2021, 5:08:28 PM] [eWeLink] [Porton ] could not be initialised as Cannot read property 'context' of undefined at new deviceGarageOne (/usr/lib/node_modules/homebridge-ewelink/lib/device/simulation/garage-one.js:53:30).**
[5/10/2021, 5:08:28 PM] [eWeLink] [Sensor entrada] initialising with options {"disableDeviceLogging":false,"lowBattThreshold":25}.
[5/10/2021, 5:08:28 PM] [eWeLink] [Sensor entrada] initialised and LAN mode unavailable as not supported.
[5/10/2021, 5:08:28 PM] [eWeLink] [Sensor cocina] initialising with options {"disableDeviceLogging":false,"lowBattThreshold":25}.
[5/10/2021, 5:08:28 PM] [eWeLink] [Sensor cocina] initialised and LAN mode unavailable as not supported.
[5/10/2021, 5:08:28 PM] [eWeLink] [Sensor ventana derecha] initialising with options {"disableDeviceLogging":false,"lowBattThreshold":25}.
[5/10/2021, 5:08:28 PM] [eWeLink] [Sensor ventana derecha] initialised and LAN mode unavailable as not supported.
[5/10/2021, 5:08:30 PM] [eWeLink] ✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
```

**Comment by bwp91** [comment]
Thanks for this. What is the name of the device in this list that is the DW2 sensor you use for the garage door?

**Comment by xnonim** [comment]
for some reason it doesn't appear in that log, I restart homebridge again, and here is the DW2 sensor

[5/11/2021, 10:47:21 PM] [eWeLink] [**Sensor porton** ] initialised and LAN mode unavailable as not supported.

**Comment by xnonim** [comment]
sorry, I just realize why the DW2 sensor was not appearing before, I had it in "ignored devices", and after deleting it from there, the garage door is working.
Im really sorry for making lose your time in this. really appreciate your quick help, and again, sorry.

**Comment by bwp91** [comment]
hey no worries.
out of interest why did you have it in the ignored devices, were you trying to hide the sensor in homekit?

**Comment by xnonim** [comment]
exactly, it appears in home app, but as I use it like a sensor for the garage door, I really don't "use it".

**Comment by bwp91** [comment]
I will look into a config option for hiding this sensor when used with a garage door and get back to you.

**Comment by xnonim** [comment]
awesome, that would be really cool. thanks again.

**Comment by bwp91** [comment]
any chance we could message on discord?

https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
Or if you are able to update to the beta version of the plugin, and then take a look in your config, you should see this new option 'Hide Sensor':

<img alt="Screenshot 2021-05-13 at 15 47 02" src="https://user-images.githubusercontent.com/43026681/118142851-acfb0b80-b402-11eb-89c5-3829321d625e.png">


Please bear in mind I cannot test the changes I have made since I do not own a DW2 device.

**Comment by xnonim** [comment]
So sorry not answer before, I'm going to try this right now

**Comment by xnonim** [comment]
Ok, so I just installed the beta 6.6.1-beta5, and tried to hide the sensor, but it still appear. I tried restarting homebridge, my phone but it still appear in home app.

Sorry the delay, I can sign up in discord if that help you, since I don't use it.

Greetings

**Comment by MoTechnicalities** [comment]
Put your garage opener device into the ignored devices list and reboot. Then remove it from the ignored devices list and reboot again and The two devices (opener and state sensor) will recombine in HomeKit to one garage simulation.
![image](https://user-images.githubusercontent.com/68468472/119271179-71183100-bbce-11eb-9dbc-0ac34f55f0b0.jpeg)

**Comment by xnonim** [comment]
Hi, no that it's solved right now, and if I hide the sensor, the garage door says it is "incompatible" in home app.

**Comment by bwp91** [comment]
any error messages in the logs when homebridge loads?
