### ISSUE TITLE
device update failed as it is unreachable at /homebridge/node_modules/homebridge-ewelink/lib/index.js:1434:19.

### ISSUE THREAD

**Issue by kamaruszamanjufri** [bwp91/homebridge-ewelink#255]
### What issue do you have? Please be as thorough and explicit as possible.

[5/17/2021, 6:19:30 PM] [eWeLink] [Ventilation Abah Mama] device update failed as it is unreachable at /homebridge/node_modules/homebridge-ewelink/lib/index.js:1434:19.

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

1

* Which version of Homebridge/HOOBS do you have?

1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Docker in Synology
Node.js Version | v14.17.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

homebridge-ewelink v6.6.0

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

POW_R2

### Please paste any relevant logs below.

[5/17/2021, 6:34:56 PM] [eWeLink] [Ventilation Hall 1]  current power [0W] current voltage [245.52V] current current [0A].
[5/17/2021, 6:34:56 PM] [eWeLink] [Ventilation Hall 1]  current power [0.00W] current voltage [245.52V] current current [0.00A].
[5/17/2021, 6:35:10 PM] [eWeLink] [Washer]  current power [0W] current voltage [237.34V] current current [0A].
[5/17/2021, 6:35:10 PM] [eWeLink] [Washer]  current power [0.00W] current voltage [237.34V] current current [0.00A].
[5/17/2021, 6:35:36 PM] [eWeLink] [Ventilation Abah Mama] device update failed as it is unreachable at /homebridge/node_modules/homebridge-ewelink/lib/index.js:1434:19.
[5/17/2021, 6:35:36 PM] [eWeLink] [Washer]  current power [0W] current voltage [237.34V] current current [0A].
[5/17/2021, 6:35:36 PM] [eWeLink] [Washer]  current power [0.00W] current voltage [237.34V] current current [0.00A].
[5/17/2021, 6:35:37 PM] [eWeLink] [Water Pump]  current power [0W] current voltage [242.52V] current current [0A].
```

```

**Comment by bwp91** [comment]
“unreachable” error is normally a network issue,

* the device being offline at the time of controlling the device 
* your homebridge instance not connected to the internet at the time of controlling the device 

The iFan device doesn’t support LAN control so an internet connection is necessary when controlling the device, both the device and your homebridge instance require internet access whenever controlling a device

**Comment by kamaruszamanjufri** [comment]
Noted on the connectivity.
But the log is not consistent with others that utilise the same device.
It is POW_R2 not IFan03.

[5/19/2021, 7:04:08 AM] [eWeLink] [Ventilation Office] current state [off].

Ventilation Office is using BasicR2, but the logs doesn't show “unreachable” when I turn it off.


[5/19/2021, 7:04:02 AM] [eWeLink] [Water Pump]  current power [0.00W] current voltage [247.31V] current current [0.00A].
[5/19/2021, 7:04:03 AM] [eWeLink] [Ventilation Office] current state [off].
[5/19/2021, 7:04:05 AM] [eWeLink] [Ventilation Office] current state [on].
[5/19/2021, 7:04:08 AM] [eWeLink] [Ventilation Office] current state [off].
[5/19/2021, 7:04:30 AM] [eWeLink] [Water Pump]  current power [0W] current voltage [247.95V] current current [0A].
[5/19/2021, 7:04:30 AM] [eWeLink] [Water Pump]  current power [0.00W] current voltage [247.96V] current current [0.00A].

**Comment by bwp91** [comment]
The BASICR2 is a device that supports local control, meaning even without an internet connection, the plugin can control the device. The iFan device does not support this mode.

It would be easier to see what is going on if you turned on plugin debug mode, then in the logs you will be able to see whether the plugin is using local control or internet control to access the devices.
