### ISSUE TITLE
DualR3 not syncing with homebridge

### ISSUE THREAD

**Issue by gVes** [bwp91/homebridge-ewelink#274]
### What issue do you have? Please be as thorough and explicit as possible.
Hi. I set up a Sonoff DualR3 on a curtain motor. Linked and calibrated with the ewelink app no issues. 
After configuring on homebridge though, I can control the curtain in HomeKit, but the positions do not seem to update.
If I close the curtain, HomeKit keeps hanging on "closing" as the screenshot below. If I restart homebridge server, then the position is correctly updated.

<img width="114" alt="Screenshot 2021-07-03 at 00 03 44" src="https://user-images.githubusercontent.com/86857167/124332685-51dbce80-db92-11eb-9796-c4fc4b37a79d.png">

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 

Homebridge + config-ui

* Which version of Homebridge/HOOBS do you have?

1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi
Node.js Version v14.17.1
Npm Version v7.17.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

6.8.0
Only tried on this version

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff DualR3

### Please paste any relevant logs below.

```
"multiDevices": [
                {
                    "deviceId": "xxxxxxxxxxx",
                    "label": "Bedroom Shutter"
                }
            ],
```

**Comment by bwp91** [comment]
Hi @gVes 

The home app should remove the “opening” or “closing” status when the curtain finishes moving.

Please can you turn on debug logging in the plugin settings, then close the curtain from
opened, and get me all the logs that appear from clicking the icon to close until the curtain has fully closed?

Thanks

**Comment by bwp91** [comment]
Does the issue only occur when closing the curtain? (ie opening works okay)

**Comment by gVes** [comment]
Hi @bwp91 

When the curtain is open, and I close it, it hangs on "closing". If I restart Homebridge while the curtain is closed, then the position is updated, and if I then open it, it would hang on "opening".

Here is the log, not much going on. I closed the curtain fully. Then reopened them.

[03/07/2021, 15:41:30] [eWeLink] [Bedroom Gate - New Wing] current position [100%].
[03/07/2021, 15:42:30] [eWeLink] [Bedroom Gate - New Wing] current position [0%].
[03/07/2021, 15:43:04] [eWeLink] [Bedroom Gate - New Wing] current position [100%].

As the screenshot below shows, also in homebridge when I closed the curtain the label still shows it as open, even thought the icon shows it as closed.

<img width="167" alt="Screenshot 2021-07-03 at 15 43 09" src="https://user-images.githubusercontent.com/86857167/124356680-847bda80-dc17-11eb-81b8-f7b1c67628f1.png">
<img width="172" alt="Screenshot 2021-07-03 at 15 43 01" src="https://user-images.githubusercontent.com/86857167/124356684-86de3480-dc17-11eb-84b6-acc48e5135e4.png">

**Comment by bwp91** [comment]
I need to see the logs with plugin debug setting on, to see what’s really going on.

With plugin debug on (via the plugin settings) there will be more info in the logs, the data that is sent to and received from the device

**Comment by gVes** [comment]
Sorry, I am new to this whole homebridge scene. This is what I get from a Close and Reopen cycle:

```
[03/07/2021, 16:44:42] [eWeLink] Web socket host received [eu-pconnect3.coolkit.cc].
[03/07/2021, 16:44:44] [eWeLink] LAN discovery starting.
[03/07/2021, 16:44:44] [eWeLink] Sending WS login request.
[03/07/2021, 16:44:44] [eWeLink] WS login successful.
[03/07/2021, 16:44:47] [eWeLink] LAN discovery complete.
[03/07/2021, 16:44:47] [eWeLink] LAN monitoring started.
[03/07/2021, 16:44:47] [eWeLink] [Bedroom Gate - New Wing] initialising with options {"disableDeviceLogging":false}.
[03/07/2021, 16:44:47] [eWeLink] [Bedroom Gate - New Wing] current position [100%].
[03/07/2021, 16:44:47] [eWeLink] [Bedroom Gate - New Wing] initialised and found locally with IP [192.168.101.158].
[03/07/2021, 16:44:47] [eWeLink] [Pool Pump] initialising with options {"disableDeviceLogging":false,"offset":0}.
[03/07/2021, 16:44:47] [eWeLink] [Pool Pump] initialised and found locally with IP [192.168.101.103].
[03/07/2021, 16:44:49] [eWeLink] ✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW
[03/07/2021, 16:45:57] [eWeLink] [Bedroom Gate - New Wing] sending update {"location":0}.
[03/07/2021, 16:45:57] [eWeLink] [Bedroom Gate - New Wing] reverting to web socket as device/command not available via LAN mode at connectionLAN.sendUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/connection/lan.js:197:15).
[03/07/2021, 16:45:58] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":100,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:45:58] [eWeLink] [Bedroom Gate - New Wing] current position [0%].
[03/07/2021, 16:46:00] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":88,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:00] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":88,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:02] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":77,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:02] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":77,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:04] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":65,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:04] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":65,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:06] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":53,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:07] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":53,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:08] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":42,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:09] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":42,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:10] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":42,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:10] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":30,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:11] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":30,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:12] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":30,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:13] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":18,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:13] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":18,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:14] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":18,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:15] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":7,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:15] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":7,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:17] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:18] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:18] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"location":0,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:19] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"location":0,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:51] [eWeLink] [Bedroom Gate - New Wing] sending update {"location":100}.
[03/07/2021, 16:46:51] [eWeLink] [Bedroom Gate - New Wing] reverting to web socket as device/command not available via LAN mode at connectionLAN.sendUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/connection/lan.js:197:15).
[03/07/2021, 16:46:51] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:52] [eWeLink] [Bedroom Gate - New Wing] current position [100%].
[03/07/2021, 16:46:54] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":11,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:54] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":11,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:56] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":22,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:56] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":22,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:46:58] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":34,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:46:58] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":34,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:47:00] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":46,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:47:00] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":46,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:47:02] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":57,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:47:02] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":57,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:47:04] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":69,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:47:05] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":69,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:47:06] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":81,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:47:07] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":81,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:47:08] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":92,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:47:09] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":92,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:47:10] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":92,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:47:10] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":100,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:47:11] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":100,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:47:12] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":100,"location":100,"online":true,"updateSource":"WS"}.
[03/07/2021, 16:47:12] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":100,"location":100,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
[03/07/2021, 16:47:15] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":100,"location":100,"online":true,"updateSource":"LAN","ip":"192.168.101.158"}.
```

**Comment by bwp91** [comment]
Thanks. I think the beta version of the plugin will fix this.

Could you update to the beta version of the plugin ([instructions](https://github.com/bwp91/homebridge-ewelink/wiki/Beta-Version#homebridge-ui)), take a look at the [changelog](https://github.com/bwp91/homebridge-ewelink/blob/latest/CHANGELOG.md#change-log) before you update if you want.

After updating, restart the plugin and hopefully this issue is resolved...

PS with this beta you should also be able to fully control the device via LAN mode

**Comment by gVes** [comment]
Great stuff!! all works as expected with the beta version. Thank you!!!

**Comment by bwp91** [comment]
Excellent. Stay on the beta, and when it’s properly released then an update message will appear in the homebridge ui.
