### ISSUE TITLE
DualR3 switch issue

### ISSUE THREAD

**Issue by gVes** [bwp91/homebridge-ewelink#293]
### What issue do you have? Please be as thorough and explicit as possible.

I have installed a DUALR3 installed on a roller shutter. All works well with homebridge and homekit. I just installed a physical switch to it and there seems to be a tiny issue:
- when the shutter is closed, and I use the switch to open it, all works ok and homekit updates correctly according to the motor position.  
- when however the shutter is open and I use the switch to close it, homekit first sends me a notification saying the shutter is "opening" and then updates to the correct status once it is closed. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge

* Which version of Homebridge/HOOBS do you have?

1.3.4

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry pi zero. 
Node.js: 14.17.6
NPM: 7.23.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

8.3.3

No the issue was also present in a previous version.  

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

DUALR3

### Please paste any relevant logs below.

```

[16/09/2021, 08:18:53] [eWeLink] [Bedroom Gate - New Wing] current power [0W] current voltage [239.74V] current current [0A].
[16/09/2021, 08:19:00] [eWeLink] [Bedroom Gate - New Wing] current position [88%].
[16/09/2021, 08:19:02] [eWeLink] [Bedroom Gate - New Wing] current position [76%].
[16/09/2021, 08:19:04] [eWeLink] [Bedroom Gate - New Wing] current position [64%].
[16/09/2021, 08:19:06] [eWeLink] [Bedroom Gate - New Wing] current position [53%].
[16/09/2021, 08:19:09] [eWeLink] [Bedroom Gate - New Wing] current position [41%].
[16/09/2021, 08:19:11] [eWeLink] [Bedroom Gate - New Wing] current position [29%].
[16/09/2021, 08:19:13] [eWeLink] [Bedroom Gate - New Wing] current position [18%].
[16/09/2021, 08:19:15] [eWeLink] [Bedroom Gate - New Wing] current position [6%].
[16/09/2021, 08:19:17] [eWeLink] [Bedroom Gate - New Wing] current position [0%].
[16/09/2021, 08:19:18] [eWeLink] [Bedroom Gate - New Wing] current target [0%].
[16/09/2021, 08:19:25] [eWeLink] [Bedroom Gate - New Wing] current power [409.72W] current voltage [242.8V] current current [1.68A].
[16/09/2021, 08:19:25] [eWeLink] [Bedroom Gate - New Wing] current power [409.72W] current voltage [242.8V] current current [1.68A].
[16/09/2021, 08:19:26] [eWeLink] [Bedroom Gate - New Wing] current position [11%].
[16/09/2021, 08:19:27] [eWeLink] [Bedroom Gate - New Wing] current power [411.29W] current voltage [241.95V] current current [1.75A].
[16/09/2021, 08:19:27] [eWeLink] [Bedroom Gate - New Wing] current power [411.29W] current voltage [241.95V] current current [1.75A].
[16/09/2021, 08:19:28] [eWeLink] [Bedroom Gate - New Wing] current position [22%].
[16/09/2021, 08:19:30] [eWeLink] [Bedroom Gate - New Wing] current position [34%].
[16/09/2021, 08:19:31] [eWeLink] [Bedroom Gate - New Wing] current power [412.86W] current voltage [241.87V] current current [1.75A].
[16/09/2021, 08:19:33] [eWeLink] [Bedroom Gate - New Wing] current position [46%].
[16/09/2021, 08:19:34] [eWeLink] [Bedroom Gate - New Wing] current position [57%].
[16/09/2021, 08:19:37] [eWeLink] [Bedroom Gate - New Wing] current position [69%].
[16/09/2021, 08:19:39] [eWeLink] [Bedroom Gate - New Wing] current position [81%].
[16/09/2021, 08:19:41] [eWeLink] [Bedroom Gate - New Wing] current position [92%].
[16/09/2021, 08:19:43] [eWeLink] [Bedroom Gate - New Wing] current position [100%].
[16/09/2021, 08:19:43] [eWeLink] [Bedroom Gate - New Wing] current power [0W] current voltage [240.24V] current current [0.04A].
[16/09/2021, 08:19:44] [eWeLink] [Bedroom Gate - New Wing] current power [0W] current voltage [240.24V] current current [0.04A].
[16/09/2021, 08:19:44] [eWeLink] [Bedroom Gate - New Wing] current target [100%].
[16/09/2021, 08:19:45] [eWeLink] [Bedroom Gate - New Wing] current power [0W] current voltage [241.19V] current current [0A].
[16/09/2021, 08:19:45] [eWeLink] [Bedroom Gate - New Wing] current power [0W] current voltage [241.19V] current current [0A].
[16/09/2021, 08:19:47] [eWeLink] [Bedroom Gate - New Wing] current power [0W] current voltage [241.16V] current current [0A].
[16/09/2021, 08:19:47] [eWeLink] [Bedroom Gate - New Wing] current power [0W] current voltage [241.16V] current current [0A].

```

**Comment by bwp91** [comment]
Hi @gVes 

Please could you use the plugin settings to turn debug mode on, and restart.

With the shutter open, could you use the switch to close, and show me all the logs that appear when you do this? It would be helpful to see the exact data the plugin is receiving to be able to determine why it’s incorrectly showing the “opening” status.

Thanks!

**Comment by gVes** [comment]
Hi. Sorry always keep forgetting that. Here's are the debug logs. 

```
[16/09/2021, 14:34:57] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":100,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:34:59] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":88,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:34:59] [eWeLink] [Bedroom Gate - New Wing] current position [88%].
[16/09/2021, 14:34:59] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":88,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:05] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":76,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:05] [eWeLink] [Bedroom Gate - New Wing] current position [76%].
[16/09/2021, 14:35:05] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":64,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:05] [eWeLink] [Bedroom Gate - New Wing] current position [64%].
[16/09/2021, 14:35:06] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":76,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:06] [eWeLink] [Bedroom Gate - New Wing] current position [76%].
[16/09/2021, 14:35:06] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":64,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:06] [eWeLink] [Bedroom Gate - New Wing] current position [64%].
[16/09/2021, 14:35:08] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":53,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:08] [eWeLink] [Bedroom Gate - New Wing] current position [53%].
[16/09/2021, 14:35:09] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":41,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:09] [eWeLink] [Bedroom Gate - New Wing] current position [41%].
[16/09/2021, 14:35:09] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":53,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:09] [eWeLink] [Bedroom Gate - New Wing] current position [53%].
[16/09/2021, 14:35:09] [eWeLink] [Bedroom Gate - New Wing] receiving update {"current_00":0,"voltage_00":23431,"actPow_00":0,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:09] [eWeLink] [Bedroom Gate - New Wing] current power [0W] current voltage [234.31V] current current [0A].
[16/09/2021, 14:35:09] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":41,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:09] [eWeLink] [Bedroom Gate - New Wing] current position [41%].
[16/09/2021, 14:35:10] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":29,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:10] [eWeLink] [Bedroom Gate - New Wing] current position [29%].
[16/09/2021, 14:35:10] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":29,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:12] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":18,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:12] [eWeLink] [Bedroom Gate - New Wing] current position [18%].
[16/09/2021, 14:35:14] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":18,"current_01":162,"voltage_01":23611,"actPow_01":36988,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:14] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":6,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:14] [eWeLink] [Bedroom Gate - New Wing] current position [6%].
[16/09/2021, 14:35:15] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":6,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:16] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:16] [eWeLink] [Bedroom Gate - New Wing] current position [0%].
[16/09/2021, 14:35:17] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:18] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"location":0,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:18] [eWeLink] [Bedroom Gate - New Wing] current target [0%].
[16/09/2021, 14:35:19] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"location":0,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:19] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"location":0,"current_01":0,"voltage_01":23616,"actPow_01":0,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:50] [eWeLink] [Shutter - Old Wing] sending update {"uiActive":{"outlet":0,"time":120}}.
[16/09/2021, 14:35:50] [eWeLink] [Shutter - Old Wing] reverting to web socket as device/command not available via LAN mode at connectionLAN.sendUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/connection/lan.js:231:15).
[16/09/2021, 14:35:50] [eWeLink] [Bedroom Gate - New Wing] sending update {"uiActive":{"outlet":0,"time":120}}.
[16/09/2021, 14:35:50] [eWeLink] [Bedroom Gate - New Wing] reverting to web socket as device/command not available via LAN mode at connectionLAN.sendUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/connection/lan.js:231:15).
[16/09/2021, 14:35:50] [eWeLink] [Shutter - Old Wing] receiving update {"currLocation":100,"location":100,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:50] [eWeLink] [Pool Pump] sending update {"uiActive":120}.
[16/09/2021, 14:35:50] [eWeLink] [Pool Pump] reverting to web socket as device/command not available via LAN mode at connectionLAN.sendUpdate (/usr/local/lib/node_modules/homebridge-ewelink/lib/connection/lan.js:231:15).
[16/09/2021, 14:35:50] [eWeLink] [Shutter - Old Wing] receiving update {"current_00":0,"voltage_00":23805,"actPow_00":0,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:50] [eWeLink] [Shutter - Old Wing] current power [0W] current voltage [238.05V] current current [0A].
[16/09/2021, 14:35:50] [eWeLink] [Bedroom Gate - New Wing] receiving update {"currLocation":0,"location":0,"online":true,"updateSource":"LAN"}.
[16/09/2021, 14:35:51] [eWeLink] [Bedroom Gate - New Wing] receiving update {"current_00":0,"voltage_00":23613,"actPow_00":0,"online":true,"updateSource":"WS"}.
[16/09/2021, 14:35:51] [eWeLink] [Bedroom Gate - New Wing] current power [0W] current voltage [236.13V] current current [0A].
```

**Comment by bwp91** [comment]
Is the physical switch you have installed like another sonoff device? Is it with a scene/automation that is controls the dualr3? how does it work?

**Comment by gVes** [comment]
It's not with a scene. It's a wired switch connected to the DUALR3's switch ports. The switch is not smart in any way. 
![image](https://user-images.githubusercontent.com/86857167/133615813-1c732a0c-c965-4de7-8902-9caaa4204c99.jpg)

**Comment by bwp91** [comment]
Sorry for delay in getting back to you.

Could we message in discord about this?

https://discord.gg/cMGhNtZ3tW
