### ISSUE TITLE
SmartWise Zigbee Bulbs paired to Sonoff Zigbee Bridge Pro not supported in Homebridge

### ISSUE THREAD

**Issue by ssgtvik** [bwp91/homebridge-ewelink#408]
### What issue do you have? Please be as thorough and explicit as possible.

SmartWise Zigbee RGBW Bulbs(Star Navi XH-001B) paired to Sonoff Zigbee Bridge Pro not supported in Homebridge
SmartWise bulb paired to Sonoff Zigbee bridge PRO. Works perfectly through Ewelink App. Not supported error in Homebridge. And SONOFF Zigbee motion sensor doesn't show the HomeKit, it is visible in Ewelink and Homebridge.

### Details of your setup.

* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

homebridge-config-ui-x v4.50.1

* Which version of Homebridge/HOOBS do you have?

Homebridge v1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspebby Pi Zero W
Node.js - latest
NPM - latest

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

homebridge-ewelink v10.0.0
I didn't use anything else

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

SmartWise Zigbee RGBW Bulbs(Star Navi XH-001B)

### Please paste any relevant logs below.

```
[Kitchen bulb] is not supported, do create a GitHub issue with the following info:
[3258] {"bindInfos":{},"subDevId":"5cf4b323004b12003258","parentid":"100163f6bd","switch":"on","colorMode":"cct","colorTemp":64,"cctBrightness":77,"hue":55,"saturation":40,"rgbBrightness":100}.

[ZBBridge-P] is not supported, do create a GitHub issue with the following info:
[168] {"bindInfos":{},"version":8,"sledOnline":"on","staMac":"0CDC7E30EF24","rssi":-26,"zled":"on","buzzerAlarm":{"mode":"stop"},"hostVersion":"1.1.0","coordinatorVersion":"2.7.12","subDevMaxNum":128,"fwVersion":"1.1.0","subDevices":[{"subDevId":"f0f51825004b12001770","deviceid":"a480033a08","uiid":"1770","index":0},{"subDevId":"dc3b1325004b12001770","deviceid":"a480033a0e","uiid":"1770","index":0},{"subDevId":"8fbc1325004b12001770","deviceid":"a480033a11","uiid":"1770","index":0},{"subDevId":"d2431925004b12001770","deviceid":"a480033a13","uiid":"1770","index":0},{"subDevId":"2ea71325004b12001770","deviceid":"a480033a15","uiid":"1770","index":0},{"subDevId":"5cf4b323004b12003258","deviceid":"a480033a25","uiid":"3258","index":0},{"subDevId":"2362b726004b12007004","deviceid":"a480033a30","uiid":"7004","index":0},{"subDevId":"edd64424004b12002026","deviceid":"a480033a6d","uiid":"2026","index":0}],"addSubDevState":"off","addDevTime":180,"only_device":{"ota":"success","ota_fail_reason":0},"localScenesLists":["localScenes_0","localScenes_1"],"localScenesTimeStamp":"1662137995728","localScenes_0":{"sceneId":"63123583462462017040f180","action":"add","operations":[{"deviceid":"a480033a30","switch":"on"}],"triggers":[{"motion":1,"deviceid":"a480033a6d"}],"triggersRelation":"or"},"localScenes_1":{"sceneId":"6312368b5face15ea509c28d","action":"add","operations":[{"deviceid":"a480033a30","switch":"off"}],"triggers":[{"motion":0,"deviceid":"a480033a6d"}],"triggersRelation":"or"}}.

```

**Comment by bwp91** [comment]
Hi @ssgtvik 

Can you install the beta version of the plugin and confirm that the light appears as a lightbulb accessory in homebridge / homekit and that the log line starting in [168] (as above) is not shown when you restart homebridge?

You should be able to turn the light on and off at the moment. Brightness and colour I need to put a bit more work into

**Comment by ssgtvik** [comment]
Hi @bwp91 

I updated beta-4. Now the bulb is visible in homebridge and homekit, but there is an error when I use it.

```

[Kitchen bulb] device update failed as it is unreachable at file:///usr/local/lib/node_modules/homebridge-ewelink/lib/platform.js:1794:17.
Error: HAP Status Error: -70402
    at new HapStatusError (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:15:5)
    at default.internalStateUpdate (file:///usr/local/lib/node_modules/homebridge-ewelink/lib/device/zigbee/light-rgb-cct.js:84:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[03/09/2022, 18:12:24] [eWeLink] Child bridge process ended

```

**Comment by bwp91** [comment]
is this turning it on and off?
Can you use the plugin settings to turn on debug logging, restart homebridge, then use the ewelink app to control the device (turn it on and off) and post here the logs that appear in homebridge when you do this?

**Comment by ssgtvik** [comment]
I replaced the raspberry pi zero w with a raspberry pi zero w 2. Since then, the error has not occurred. Thank you for your help so far. I hope there will be brightness and color adjustment soon.

**Comment by bwp91** [comment]
I also need these logs I mentioned above for brightness and colour control.

Are you able to get logs that appear for performing these actions in the ewelink app:

- turning brightness to 100%
- choose an rgb colour (like red)
- then brightness to 50%
- then choosing another rgb colour 
- then switching to a colour temperature 
- then choosing another colour temperature

please stick to this order so I see commands / payloads for different combinations of different modes and and also changes within the same mode

**Comment by ssgtvik** [comment]
### I hope this is good:

```
[04/09/2022, 13:56:18] [eWeLink] [Kichen bulb] initialising with options {“brightnessStep”:1,”logging”:”debug”}.
[04/09/2022, 13:56:18] [eWeLink] [Kichen bulb] initialised and LAN mode unavailable as not discovered/supported [3258:ZigbeeColorTunableWhiteLight].

[04/09/2022, 13:57:28] [eWeLink] [Kichen bulb] receiving update {“rgbBrightness”:77,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:57:28] [eWeLink] [Kichen bulb] receiving update {“switch”:”on”,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:57:28] [eWeLink] [Kichen bulb] current state [on].
[04/09/2022, 13:57:28] [eWeLink] [Kichen bulb] receiving update {“colorMode”:”cct”,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:57:28] [eWeLink] [Kichen bulb] receiving update {“colorTemp”:64,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:57:30] [eWeLink] [Kichen bulb] receiving update {“hue”:55,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:57:30] [eWeLink] [Kichen bulb] receiving update {“saturation”:40,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:57:30] [eWeLink] [Kichen bulb] receiving update {“switch”:”on”,”online”:true,”updateSource”:”WS”}.

[04/09/2022, 13:57:42] [eWeLink] [Kichen bulb] receiving update {“colorMode”:”cct”,”switch”:”on”,”cctBrightness”:100,”online”:true,

[04/09/2022, 13:57:44] [eWeLink] [Kichen bulb] receiving update {“cctBrightness”:100,”online”:true,”updateSource”:”WS”}.

[04/09/2022, 13:57:51] [eWeLink] [Kichen bulb] receiving update {“colorMode”:”rgb”,”switch”:”on”,”rgbBrightness”:77,”hue”:55,”saturation”:40,”online”:true,”updateSource”:”WS”}.

[04/09/2022, 13:57:52] [eWeLink] [Kichen bulb] receiving update {“rgbBrightness”:77,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:57:52] [eWeLink] [Kichen bulb] receiving update {“hue”:53,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:57:53] [eWeLink] [Kichen bulb] receiving update {“switch”:”on”,”hue”:357,”saturation”:40,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:57:55] [eWeLink] [Kichen bulb] receiving update {“hue”:356,”online”:true,”updateSource”:”WS”}.

[04/09/2022, 13:57:55] [eWeLink] [Kichen bulb] receiving update {“hue”:356,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:58:07] [eWeLink] [Kichen bulb] receiving update {“rgbBrightness”:47,”online”:true,”updateSource”:”WS”}.

[04/09/2022, 13:58:10] [eWeLink] [Kichen bulb] receiving update {“switch”:”on”,”hue”:249,”saturation”:40,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:58:12] [eWeLink] [Kichen bulb] receiving update {“hue”:248,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:58:13] [eWeLink] [Kichen bulb] receiving update {“colorMode”:”cct”,”switch”:”on”,”cctBrightness”:100,”colorTemp”:64,”online”:true,”updateSource”:”WS”}.

[04/09/2022, 13:58:15] [eWeLink] [Kichen bulb] receiving update {“cctBrightness”:100,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:58:15] [eWeLink] [Kichen bulb] receiving update {“colorMode”:”cct”,”switch”:”on”,”colorTemp”:0,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:58:15] [eWeLink] [Kichen bulb] receiving update {“colorTemp”:0,”online”:true,”updateSource”:”WS”}.

[04/09/2022, 13:58:21] [eWeLink] [Kichen bulb] receiving update {“colorMode”:”cct”,”switch”:”on”,”colorTemp”:100,”online”:true,”updateSource”:”WS”}.

[04/09/2022, 13:58:23] [eWeLink] [Kichen bulb] receiving update {“colorTemp”:100,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:58:26] [eWeLink] [Kichen bulb] receiving update {“colorMode”:”cct”,”switch”:”on”,”colorTemp”:56,”online”:true,”updateSource”:”WS”}.

[04/09/2022, 13:58:33] [eWeLink] [Kichen bulb] receiving update {“switch”:”off”,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:58:33] [eWeLink] [Kichen bulb] current state [off].
[04/09/2022, 13:58:34] [eWeLink] [Kichen bulb] receiving update {“switch”:”off”,”online”:true,”updateSource”:”WS”}.
[04/09/2022, 13:58:34] [eWeLink] [Kichen bulb] receiving update {“colorTemp”:56,”online”:true,”updateSource”:”WS”}.

```

**Comment by ssgtvik** [comment]
Did I send the correct information? I would like to comment with another device. And I would also help with the Hungarian translation of the plugin if you think so.

**Comment by bwp91** [comment]
hiya yes this is the info i need, just need go get round to implementing it 🙂
what are you comments on the other device?

**Comment by ssgtvik** [comment]
I add nspanel as a thermostat to the plugin, but it does not appear in homekit and homebridge. Only switch available.
I also tried it in Hoobs, but there only one switch appears and switches at the same time.
If you think we can continue the conversation on discord.

![Képernyőfotó 2022-09-07 - 20 09 45](https://user-images.githubusercontent.com/95101963/188949117-9e097f35-fe19-4037-b8bf-16bf223b5ceb.png)
![Képernyőfotó 2022-09-07 - 20 10 33](https://user-images.githubusercontent.com/95101963/188949134-f8accca6-a074-460e-b30a-469ef4e62645.png)
![Képernyőfotó 2022-09-07 - 20 11 45](https://user-images.githubusercontent.com/95101963/188949140-54ef1c49-da41-4128-a9f1-57e1e6462a06.png)

**Comment by bwp91** [comment]
Hi @ssgtvik 
I have sent you a message on discord but not sure if you are still on there?
I have a bit of time today to get this bulb working, would be great to message you if you have some time.
Thanks!

**Comment by bwp91** [comment]
Latest beta of the plugin should allow for brightness, colour and colour temperature. Let me know if it’s working okay. Still need to add the adaptive lighting
