### ISSUE TITLE
Sonoff switchman M5-3C (same UUID as another bridged Accessory)

### ISSUE THREAD

**Issue by KitanaShaw** [bwp91/homebridge-ewelink#416]
### What issue do you have? Please be as thorough and explicit as possible.
i have Sonoff switchman M5-3C and an older TX-3C
the older T3UK3C shows 1 master switch + 3 individual switches for each channel and it works flawlessly
my new M5-3C switches when they are imported i only get 1 switch (even though it is 3 gang switch) but it doesnt work  
and there is log messages about both switches (ignore the part where i have my older TX-3C switches disconnected)

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge on docker container on Synology NAS

* Which version of Homebridge/HOOBS do you have?

1.5.0 latest (and i tried the beta version aswell 1.5.1-beta. 1)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Synology NAS
i dont know what Node.js/NPM version but one of the logs shows 

```
The plugin "homebridge-ewelink" requires Node.js version of ^14.20.1 || ^16.17.1 which does not satisfy the current Node.js version of v16.16.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
```

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

v10.1.0  (i tried v10.1.01-beta.2 but same issue)

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

Sonoff Switchman M5-3C

### Please paste any relevant logs below.

```
[9/30/2022, 6:40:33 PM] [eWeLink] Fetching devices from eWeLink home/id [My Home] [********].
[9/30/2022, 6:40:34 PM] [eWeLink] Web socket host received [as-pconnect1.coolkit.cc].
[9/30/2022, 6:40:35 PM] [eWeLink] Sending WS login request.
[9/30/2022, 6:40:35 PM] [eWeLink] LAN discovery starting.
[9/30/2022, 6:40:36 PM] [eWeLink] WS login successful.
[9/30/2022, 6:40:38 PM] [eWeLink] LAN discovery complete.
[9/30/2022, 6:40:38 PM] [eWeLink] LAN monitoring started.
[9/30/2022, 6:40:39 PM] [eWeLink] [M5-3C] could not be added to Homebridge as Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7a5fa46f-c0f8-4c3b-b908-6b063cf1d1d7 at Bridge.Accessory.addBridgedAccessory (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:594:15).
[9/30/2022, 6:40:39 PM] [eWeLink] [M5-3C] could not be initialised as Cannot read properties of undefined (reading 'eweDeviceId') at new default (file:///homebridge/node_modules/homebridge-ewelink/lib/device/switch-man.js:17:62).
[9/30/2022, 6:40:39 PM] [eWeLink] [M5-3C 1] could not be added to Homebridge as Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7b03cdeb-dfea-4a93-9b67-d1c9c0c9d7cc at Bridge.Accessory.addBridgedAccessory (/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:594:15).
[9/30/2022, 6:40:39 PM] [eWeLink] [M5-3C 1] could not be initialised as Cannot read properties of undefined (reading 'eweDeviceId') at new default (file:///homebridge/node_modules/homebridge-ewelink/lib/device/switch-man.js:17:62).
[9/30/2022, 6:40:39 PM] [eWeLink] [Main Lights] initialising with options {"inchChannels":"","inUsePowerThreshold":0,"logging":"debug","showAs":"default"}.
[9/30/2022, 6:40:39 PM] [eWeLink] [Main Lights] has been reported [offline] via WS.
[9/30/2022, 6:40:39 PM] [eWeLink] [Main Lights] initialised and LAN mode unavailable as not discovered/supported [8:TX3C].
[9/30/2022, 6:40:39 PM] [eWeLink] [Side Lights] initialising with options {"inchChannels":"","inUsePowerThreshold":0,"logging":"debug","showAs":"default"}.
[9/30/2022, 6:40:39 PM] [eWeLink] [Side Lights] has been reported [offline] via WS.
[9/30/2022, 6:40:39 PM] [eWeLink] [Side Lights] initialised and LAN mode unavailable as not discovered/supported [8:TX3C].
[9/30/2022, 6:40:41 PM] [eWeLink] ✓ Setup complete. This plugin has been made with ♥ by bwp91 from the UK!
```

**Comment by bwp91** [comment]
Hi @KitanaShaw 

Please try the newest beta version of the plugin :)

**Comment by KitanaShaw** [comment]
it works now

thank you very much!
