### ISSUE TITLE
HB - randomly No respone in homekit app

### ISSUE THREAD

**Issue by JacekKac** [bwp91/homebridge-ewelink#484]
HB running with few plugins one of them is homebridge-ewelink v10.4.0. Few sonoff devices linked, everythink is running OK but randomly homekit app gives no responding for this accessories - in the same time they are working in web panel of homebride and i can use them. After restarting homebridge devices are once again responding and working ok also in homekit app.

Any ideas how to debug/fix this ?

p.s. at the same time other plugins are working fine in home app

**Logs:** 

nothing special in the logs sonoff devices are up and running (reporting)

**config:** 
{
            "name": "eWeLink",
            "username": "...",
            "password": "...",
            "mode": "auto",
            "debug": false,
            "language": "en",
            "ignoredHomes": "6208df3c1882c9000992d8fb",
            "platform": "eWeLink"
        },

**Environment**
OS: PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

Software: [v1.6.0]

Node:v14.21.3

npm: 6.14.18

Process Supervisor
systemd

**Comment by Themaster312** [comment]
Same here with Node 18.16

**Comment by Themaster312** [comment]
I have Downgrade Homebridge to 1.5.1 than its works

**Comment by JacekKac** [comment]
@Themaster312 issues also with ewlink plugin ?

**Comment by Themaster312** [comment]
Yes

**Comment by Themaster312** [comment]
I have downgrade my Homebridge to 1.5.1 and it works

**Comment by Themaster312** [comment]
if someone gets it running with 1.6 write here then I can do the update again

**Comment by bwp91** [comment]
i am running homebridge 1.6 with the plugin fine 😄

**Comment by Themaster312** [comment]
I'm running 1.6 for 2 hours or until a restart and 1.5.1 has been running for 2 days now

I just don't know why it's like that for me, there are no errors, nothing

**Comment by bwp91** [comment]
can you post your config? please hash out %%% any emails and passwords etc

**Comment by Themaster312** [comment]
{
    "bridge": {
        "name": "Homebridge D734",
        "username": "0E:11:F7:75:D4:ED",
        "port": 51792,
        "pin": "435-22-266",
        "advertiser": "ciao"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8681,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "eWeLink",
            "username": "….",
            "password": „……",
            "mode": "auto",
            "debug": false,
            "language": "en",
            "platform": "eWeLink"
        }
    ]
}

**Comment by bwp91** [comment]
oh so a pretty standard config 🧐

**Comment by Themaster312** [comment]
Yes and 39 devices are also loaded and either run for 2 hours or after a restart there is no response ,in Homebridge ist works but everything just doesn't work in the HomeKit app After Thies Time of a restart

**Comment by bwp91** [comment]
the issue could be down to many reasons so what i suggest may work for one but not another. (disclosure!)

if you go to the homebridge settings what do you have as the mDNS advertiser?

**Comment by Themaster312** [comment]
Ciao as advertiser

**Comment by Themaster312** [comment]
and after a restart all are without response, if I empty the cache then everything goes again for the time x

**Comment by JacekKac** [comment]
i am using avahi, it could be connected to 1.6 code because i used < 1.6  it earlier without problems, not sure the exact dates of upgrade/problems but could be worth of checking

**Comment by bwp91** [comment]
just wanted to initially check that you are using a different ewelink account credentials in the plugin compared to the ewelink app?

if you use the same in both places then stuff is gonna go wrong

**Comment by JacekKac** [comment]
As i said plugin is working in homebridge UI addon even if HomeKit shows No responding. In my case its not connected with configuration

**Comment by bwp91** [comment]
yeah alright i’m just trying to rule stuff out first

**Comment by monkeycatdog** [comment]
Have something similar, 
Time to time success but there is an error in the logs

`[9/12/2023, 12:07:58 AM] [eWeLink] [Kitchen lighting ] device update failed as request timeout [504] at default.sendUpdate (file:///usr/local/lib/node_modules/homebridge-ewelink/lib/connection/ws.js:334:19) at default.sendUpdate (file:///usr/local/lib/node_modules/homebridge-ewelink/lib/connection/ws.js:341:15)`
