### ISSUE TITLE
Sonoff TX Ultimate Error

### ISSUE THREAD

**Issue by lcmds** [bwp91/homebridge-ewelink#507]
### What issue do you have? Please be as thorough and explicit as possible.

I'm getting this error when I try to turn my lights on using Homebridge UI through the Accessories TAB. [Office Lights ] device update failed as unknown WS response [400] at default.sendUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/connection/ws.js:339:19) at default.sendUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/connection/ws.js:344:15). Device Model T5-1C-86 (SN-ESP32D0-T5-01). Let me know if you need further information.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI

* Which version of Homebridge/HOOBS do you have?

[v1.6.1]

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Linux Debian / Node.js Version | v18.16.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?

homebridge-ewelink v11.0.0
Actually, the TX Ultimate switches are pretty new and I have all versions installed 1,2 and 3 gang. It turns out that this one never worked through the Homebridge UI.

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.

T5-3C-86 (SN-ESP32D0-T5-01)
T5-2C-86 (SN-ESP32D0-T5-01)
T5-1C-86 (SN-ESP32D0-T5-01)

### Please paste any relevant logs below.

```
[7/24/2023, 12:21:09 PM] [eWeLink] [Office Lights ] device update failed as unknown WS response [400] at default.sendUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/connection/ws.js:339:19) at default.sendUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/connection/ws.js:344:15).
```
Node.js Version	[v18.16.0](https://homebridge.io/w/JTKEF)

**Comment by duarteffc** [comment]
I'm having the same issue on my side. Tried different versions of the plugin and even of the node. Nothing worked.

**Comment by bwp91** [comment]
@lcmds @duarteffc 

am i correct in assuming that you are using the plugin in lan only mode?

**Comment by duarteffc** [comment]
@bwp91 I am using Hybrid mode

**Comment by duarteffc** [comment]
I just checked with Homebridge UI version 1.6.0 and it worked using the latest version of the plugin.

**Comment by lcmds** [comment]
@bwp91 same thing here, I'm using Hybrid mode.

**Comment by duarteffc** [comment]
I was able to make it work. Actually, after turning it on once from the eWeLink app, it started working on the Home app again.

**Comment by lcmds** [comment]
I followed the instructions, but the issue persists. I can control the device through the eWeLink app, but there are no logs on Homebridge, and I try to control it from the Homebridge I get the same error.

**Comment by lcmds** [comment]
I've updated to the latest Beta version. It still no working when I turn it On/Off via homebridge webapp, but the error now comes with more messages as you can see bellow.

[9/12/2023, 9:27:37 AM] [eWeLink] [Office Lights ] sending update {"switch":"on"}.
[9/12/2023, 9:27:37 AM] [eWeLink] [Office Lights ] reverting to web socket as device not reachable via LAN mode at default.sendUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/connection/lan.js:157:15).
[9/12/2023, 9:27:37 AM] [eWeLink] [Office Lights ] device update failed as unknown WS response [400] at default.sendUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/connection/ws.js:337:19) at default.sendUpdate (file:///var/lib/homebridge/node_modules/homebridge-ewelink/lib/connection/ws.js:341:15).
[9/12/2023, 9:27:37 AM] [eWeLink] [Office Lights ] receiving update {"switches":[{"outlet":0,"switch":"off"}],"online":true,"updateSource":"WS"}.

**Comment by Shadowxrp** [comment]
If any of you find a fix please let us know , my tx ultimate isn’t working either. probably not supported

**Comment by duarte54** [comment]
I'm having the same issue with my TX ultimate.  any solutions yet?

Thank you
