### ISSUE TITLE
eWeLink Bridge eWeLink WARNING WS login failed as WebSocket closed with reason: undefined

### ISSUE THREAD

**Issue by trhessel** [bwp91/homebridge-ewelink#535]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

I am currently using HOOBS with the ewelink plugin where every so often I see this in the logs

eWeLink BridgeeWeLinkWARNINGWS login failed as WebSocket closed with reason: undefined (undefined). at WebSocketAsPromised._handleClose (/var/lib/hoobs/ewelinkbridge/node_modules/websocket-as-promised/src/index.js:407:19).

and control of my ewelink devices from homekit/hoobs does not work until I restart the plugin or hoobs. The problem goes away for sometimes, hours or days but comes back again. 

I am running Hoobs v4.3.0 on a Pi 4 and I am running v 12.1.0 of the ewelink plugin.

**Comment by bwp91** [comment]
Hi @trhessel are you using the same credentials for the ewelink app as for the plugin config?

**Comment by anon1y4012** [comment]
Same issue here, @bwp91 I am using the main credentials for the ewelink app. Happy to provide logs.

**Comment by bjornand1** [comment]
I am getting the same all the time now:

[2/12/2024, 6:36:14 AM] [eWeLink] WS login failed as WebSocket closed with reason: undefined (undefined). at WebSocketAsPromised._handleClose (/volume1/homebridge/node_modules/homebridge-ewelink/node_modules/websocket-as-promised/src/index.js:407:19).

But the connected Sonoff device still works in Apple Home, so not sure what is going on.

**Comment by Jeremesk** [comment]
Hi, I am getting this error too, and it does seem to affect Apple Home as I am getting another error when switching off my device from the app:

device update failed as Web socket is not open - try again after a few seconds at default.sendUpdate (file:///usr/local/lib/node_modules/homebridge-ewelink/lib/connection/ws.js:345:13).

**Comment by ktahatastan** [comment]
i have same issue

**Comment by itaiLandau** [comment]
Anyone got it fixed?
Getting the same error continuously and no response in both HomeKit and homebridge but if I restart the plugin then the error goes away and everything works for a about a day.
