### ISSUE TITLE
Sonoff Dual is Seen as a 4Ch

### ISSUE THREAD

**Issue by tawagny** [bwp91/homebridge-ewelink#54]
Hello , I have many Sonoff devices and they were all working fine until lately the Sonoff Dual is being identified as a 4CH devicce which blocks all of my Homebridge devices from being used in the homekit app 
here is the log i get 
[11/18/2019, 7:26:45 AM] [eWeLink] WebSocket messge received:  {"action":"update","deviceid":"100039e384","apikey":"dab78fd3-b573-48e0-ba43-f9e8603055fd","userAgent":"app","sequence":"1574054805263","ts":0,"params":{"switches":[{"switch":"off","outlet":0},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"off","outlet":3}]},"tempRec":"100039e384"}
[11/18/2019, 7:26:45 AM] [eWeLink] Error updating non-exist accessory with deviceId [100039e384CH1].
[11/18/2019, 7:26:45 AM] [eWeLink] Error updating non-exist accessory with deviceId [100039e384CH2].
[11/18/2019, 7:26:45 AM] [eWeLink] Error updating non-exist accessory with deviceId [100039e384CH3].
[11/18/2019, 7:26:45 AM] [eWeLink] Error updating non-exist accessory with deviceId [100039e384CH4].
eWeLink] WebSocket messge received:[eWeLink] Error updating non-exist accessory with deviceId

**Comment by tawagny** [comment]
Model Dual_R@
Firmeware PSF-BO4-GL

**Comment by tawagny** [comment]
[11/18/2019, 10:41:38 AM] [eWeLink] WebSocket message received:  {"action":"update","deviceid":"100039a92f","apikey":"dab78fd3-b573-48e0-ba43-f9e8603055fd","userAgent":"app","sequence":"1574066498334","ts":0,"params":{"switches":[{"switch":"off","outlet":0},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"off","outlet":3}]},"tempRec":"100039a92f"}
[11/18/2019, 10:41:38 AM] [eWeLink] Update message received for device [100039a92f]
[11/18/2019, 10:41:38 AM] [eWeLink] {
  action: 'update',
  deviceid: '100039a92f',
  apikey: 'dab78fd3-b573-48e0-ba43-f9e8603055fd',
  userAgent: 'app',
  sequence: '1574066498334',
  ts: 0,
  params: { switches: [ [Object], [Object], [Object], [Object] ] },
  tempRec: '100039a92f'
}

**Comment by tawagny** [comment]
possible its  cloud glitch ... I am trying everything , this is the last error I got 

[11/18/2019, 3:17:55 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 70eb4868-bc32-4937-9ee5-23c8dd386450
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:396:18)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:93:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11

**Comment by tawagny** [comment]
[11/18/2019, 5:20:19 PM] [eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Error was [Error: Parsing error : Unexpected token < in JSON at position 0, body=
 <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>
    at Object.parseBody (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/main.js:67:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
