### ISSUE TITLE
TypeError: body.filter is not a function since last thursday

### ISSUE THREAD

**Issue by imsturmdernacht** [bwp91/homebridge-ewelink#55]
Hi everybody,

since last thursday evening I get the following errors from the ewelink plugin:
Nothing has changed on the setup. The errors came out of nothing.
Any idea?

[2019-11-20 7:42:50] TypeError: body.filter is not a function
    at /usr/local/lib/node_modules/homebridge-ewelink/index.js:364:37
    at Object.parseBody (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:74:12)
    at Request._callback (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by migabc** [comment]
I have the same issue
This is causing the homebridge to crash

> Nov 28 20:42:50 raspberrypi homebridge[12796]: [11/28/2019, 8:42:50 PM] [eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Verify your configuration options. Response was [{"error":400,"msg":"params incomplete"}]
> Nov 28 20:42:50 raspberrypi homebridge[12796]: [11/28/2019, 8:42:50 PM] TypeError: body.filter is not a function
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at /usr/lib/node_modules/homebridge-ewelink/index.js:364:37
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at Object.parseBody (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:74:12)
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at Request._callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:148:26)
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at Request.self.callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:187:22)
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at Request.emit (events.js:193:13)
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at Request.<anonymous> (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:1044:10)
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at Request.emit (events.js:193:13)
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:965:12)
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at IncomingMessage.emit (events.js:198:15)
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at endReadableNT (_stream_readable.js:1139:12)
> Nov 28 20:42:50 raspberrypi homebridge[12796]: at processTicksAndRejections (internal/process/task_queues.js:81:17)
> Nov 28 20:42:50 raspberrypi homebridge[12796]: [11/28/2019, 8:42:50 PM] Got SIGTERM, shutting down Homebridge...
> Nov 28 20:42:55 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=143/n/a
> 

It seems that the protocol was changed on the server side
