### ISSUE TITLE
[eWeLink] Error: Web socket is not open

### ISSUE THREAD

**Issue by davadka** [bwp91/homebridge-ewelink#558]
### What issue do you have? Please be as thorough and explicit as possible.
Some of my accessories won't respond until I restart HB. Typically the zigbee devices I use with SmartWise Zigbee Bridge Pro.
Then they go for a while and then not again.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
 v1.8.3

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi - Node.js Version | v20.15.0

* Which version of this plugin (homebridge-ewelink) do you have? Has the issue started since upgrading from a previous version?
v12.2.0 - I dont think so.

* Which eWeLink devices do you have that are causing issues? Please include product models if applicable.
I'm not sure, I have SmartWise Zigbee Bridge Pro and child devices like Sonoff SNZB-03 or Gledopto GL-C-007P etc...

### Please paste any relevant logs below.

There are 2-3 more relevant error logs:
```
*********************************************
[21/06/2024, 08:49:51] [eWeLink] [Window 8] current power [0W] current voltage [241.23V] current current [0A].
[21/06/2024, 08:49:54] [eWeLink] Error: request timeout [504] at default.sendUpdate (file:///usr/lib/node_modules/homebridge-ewelink/lib/connection/ws.js:334:19)
    at default.sendUpdate (file:///usr/lib/node_modules/homebridge-ewelink/lib/connection/ws.js:341:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at file:///usr/lib/node_modules/homebridge-ewelink/node_modules/p-timeout/index.js:99:13
[21/06/2024, 08:49:54] [eWeLink] [Háló R4] current power [0W] current voltage [240.72V] current current [0A].
*******************************************
 [eWeLink] WS login failed [406] see https://bit.ly/hb-ewelink-errors
[21/06/2024, 08:06:45] [eWeLink] WS unknown command received.
{
  "error": 406,
  "reason": "Authentication Failed",
  "apikey": "-----------------------------",
  "sequence": "--------",
  "actionName": "userOnline",
  "params": {}
}
[21/06/2024, 08:06:47] [eWeLink] Error: Web socket is not open - try again after a few seconds
    at default.sendUpdate (file:///usr/lib/node_modules/homebridge-ewelink/lib/connection/ws.js:345:13)
    at file:///usr/lib/node_modules/homebridge-ewelink/lib/platform.js:1854:34
    at file:///usr/lib/node_modules/homebridge-ewelink/node_modules/p-timeout/index.js:99:13

```

**Comment by davadka** [comment]
I've checked https://bit.ly/hb-ewelink-errors but I don't want to believe the solution should be restarting HB/plugin frequently. 
I can confirm that I have active session only on my "main app" and HB.

**Comment by davadka** [comment]
It seems the problem solved when you log out from ewelink app and only HB using the ewelink credentials.
