### ISSUE TITLE
Please add a switch that supports multiple buttons，thank you！

### ISSUE THREAD

**Issue by 18066034545** [bwp91/homebridge-ewelink#6]
I do not speak English, is used to reproduce, I have completed a key switch access to homekit

But I have some 2 keys, 3 keys and 4 key switches on my hand. Changing homebridge can only identify a switch, and it can't be controlled. This is the state that I switch and trigger homebridge in ewelink APP. Please add a switch that supports multiple buttons.
[2018-1-16 17:18:51] [eWeLink] WebSocket messge received:  {"error":0,"deviceid":"10000b02af","apikey":"fd2b60c0-3604-4aa3-bb88-cefd92442c8e","sequence":"1516094330914"}
[2018-1-16 17:19:00] [eWeLink] WebSocket messge received:  {"action":"update","deviceid":"10002d5895","apikey":"fd2b60c0-3604-4aa3-bb88-cefd92442c8e","userAgent":"app","sequence":"1516094339883","ts":0,"params":{"switches":[{"switch":"on","outlet":0},{"switch":"off","outlet":1},{"switch":"off","outlet":2},{"switch":"on","outlet":3}]},"tempRec":"10002d5895"}
[2018-1-16 17:19:00] [eWeLink] Update message received for device [10002d5895]

[2018-1-16 17:19:01] [eWeLink] WebSocket messge received:  {"error":0,"deviceid":"10000b02af","apikey":"fd2b60c0-3604-4aa3-bb88-cefd92442c8e","sequence":"1516094340494"}
[2018-1-16 17:19:04] [eWeLink] WebSocket messge received:  {"action":"update","deviceid":"10002d5895","apikey":"fd2b60c0-3604-4aa3-bb88-cefd92442c8e","userAgent":"app","sequence":"1516094344353","ts":0,"params":{"switches":[{"outlet":0,"switch":"on"},{"outlet":1,"switch":"on"},{"outlet":2,"switch":"off"},{"outlet":3,"switch":"on"}]},"tempRec":"10002d5895"}
[2018-1-16 17:19:04] [eWeLink] Update message received for device [10002d5895]

**Comment by Trivellacipi** [comment]
I really appreciate what the developer did: it’s a great job. Thanks a lot. 

By the way i have the same problem: i have a 4CH pro (Sonoff) which is a 4 keys switch and this plugin for homebridge cannot display and update correctly the accessory. I think that there is not so much work to do in order to make it compatible.  Maybe i can help.

**Comment by aremishevsky** [comment]
Hi @Trivellacipi .

Could you please provide us a model number of your switch?
So that we can add your device in the supported devices list.

FYI: my device's model is 'PSB-B04-GL' - and it is 2 channel switch - Your model should be similar

**Comment by Trivellacipi** [comment]
Here you can see all details. It's a 4 channel switch. Thanks for the help. As you can see in the log posted by 18066034545, the Websocket replies with the information about the status of the switch, but the homebridge plugin it's not able to store and use these information.  ![image1](https://user-images.githubusercontent.com/37866825/38043940-a75fd710-32b8-11e8-836b-867bb4ceaf55.jpeg)

**Comment by aremishevsky** [comment]
@Trivellacipi I've added "PSF-A04-GL" in supported devices list as 4 switch handler.
please use the following command to install my forked homebridge-ewelink repo:
`npm i -g git+https://github.com/aremishevsky/homebridge-ewelink`

After you test it - let me know if everything works fine, so that i can create a pull-request to the source branch. (After that it will be published in some time).

**Comment by Trivellacipi** [comment]
3 Switches are correctly received, but the fourth one struggles. This is the current situation: 

```
[2018-3-28 22:46:22] [eWeLink] eWeLink HTTPS API reports that there are a total of [1] devices registered
[2018-3-28 22:46:22] [eWeLink] Evaluating if devices need to be removed...
[2018-3-28 22:46:22] [eWeLink] Verifying that all cached devices are still registered with the API. Devices that are no longer registered with the API will be removed.
[2018-3-28 22:46:22] [eWeLink] Device [Tapparella 1 CH 1] is regeistered with API. Nothing to do.
[2018-3-28 22:46:22] [eWeLink] Device [Tapparella 1 CH 2] is regeistered with API. Nothing to do.
[2018-3-28 22:46:22] [eWeLink] Device [Tapparella 1 CH 3] is regeistered with API. Nothing to do.
[2018-3-28 22:46:22] [eWeLink] Evaluating if new devices need to be added...
[2018-3-28 22:46:22] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH1] will be added
[2018-3-28 22:46:22] [eWeLink] Not adding [1000209aa1CH1] as it already exists in the cache
[2018-3-28 22:46:22] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH2] will be added
[2018-3-28 22:46:22] [eWeLink] Not adding [1000209aa1CH2] as it already exists in the cache
[2018-3-28 22:46:22] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH3] will be added
[2018-3-28 22:46:22] [eWeLink] Not adding [1000209aa1CH3] as it already exists in the cache
[2018-3-28 22:46:22] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH4] will be added
/usr/lib/node_modules/homebridge-ewelink/index.js:324
    this.log("Found Accessory with Name : [%s], Manufacturer : [%s], Status : [%s], Is Online : [%s], API Key: [%s] ", device.name + (channel ? ' CH ' + channel : ''), device.productModel, channel ? device.params.switches[channel].switch : device.params.switch, device.online, device.apikey);
                                                                                                                                                                                                                                       ^

TypeError: Cannot read property 'switch' of undefined
    at eWeLink.addAccessory (/usr/lib/node_modules/homebridge-ewelink/index.js:324:232)
    at checkIfDeviceIsAlreadyConfigured (/usr/lib/node_modules/homebridge-ewelink/index.js:186:42)
    at Map.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-ewelink/index.js:197:45
    at Object.parseBody (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:74:12)
    at Request._callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)

```

But i will try soon a new installation of homebridge and ewelink plugin. I'll post updates.

**Comment by aremishevsky** [comment]
@Trivellacipi try to remove ~/.homebridge/accessories/accessoryCache file and re-start your server

**Comment by Trivellacipi** [comment]
```
[2018-3-28 22:58:54] [eWeLink] A total of [0] accessories were loaded from the local cache
[2018-3-28 22:58:54] [eWeLink] Requesting a list of devices from eWeLink HTTPS API at [https://eu-api.coolkit.cc:8080]
[2018-3-28 22:58:54] Homebridge is running on port 51826.
[2018-3-28 22:58:55] [eWeLink] eWeLink HTTPS API reports that there are a total of [1] devices registered
[2018-3-28 22:58:55] [eWeLink] Evaluating if devices need to be removed...
[2018-3-28 22:58:55] [eWeLink] Evaluating if new devices need to be added...
[2018-3-28 22:58:55] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH1] will be added
[2018-3-28 22:58:55] [eWeLink] Found Accessory with Name : [Tapparella 1 CH 1], Manufacturer : [Sonoff 4CH Pro], Status : [off], Is Online : [true], API Key: [****************************************] 
[2018-3-28 22:58:55] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH2] will be added
[2018-3-28 22:58:55] [eWeLink] Found Accessory with Name : [Tapparella 1 CH 2], Manufacturer : [Sonoff 4CH Pro], Status : [off], Is Online : [true], API Key: [****************************************] 
[2018-3-28 22:58:55] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH3] will be added
[2018-3-28 22:58:55] [eWeLink] Found Accessory with Name : [Tapparella 1 CH 3], Manufacturer : [Sonoff 4CH Pro], Status : [off], Is Online : [true], API Key: [****************************************] 
[2018-3-28 22:58:55] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH4] will be added
/usr/lib/node_modules/homebridge-ewelink/index.js:324
    this.log("Found Accessory with Name : [%s], Manufacturer : [%s], Status : [%s], Is Online : [%s], API Key: [%s] ", device.name + (channel ? ' CH ' + channel : ''), device.productModel, channel ? device.params.switches[channel].switch : device.params.switch, device.online, device.apikey);
                                                                                                                                                                                                                                       ^

TypeError: Cannot read property 'switch' of undefined
    at eWeLink.addAccessory (/usr/lib/node_modules/homebridge-ewelink/index.js:324:232)
    at checkIfDeviceIsAlreadyConfigured (/usr/lib/node_modules/homebridge-ewelink/index.js:186:42)
    at Map.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-ewelink/index.js:197:45
    at Object.parseBody (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:74:12)
    at Request._callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:186:22)
    at Request.emit (events.js:180:13)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-ewelink/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:180:13)

```

**Comment by aremishevsky** [comment]
@Trivellacipi make `npm i -g git+https://github.com/aremishevsky/homebridge-ewelink` again and re-start your server (I've added one more extra check)

**Comment by aremishevsky** [comment]
@18066034545 please provide your model names with relations to your switch counters (like @Trivellacipi did)
Example: 
 - "XXX-XXX-XX" - 2 switches
 - "XXX-XXX-XX" - 3 switches
 - "XXX-XXX-XX" - 4 switches
We can add them so that you can use this plugin

**Comment by Trivellacipi** [comment]
Now 4 Channels are correctly seen, with their correct "on/off" value, but the procedure get stuck in the login process. 
```
[2018-3-28 23:59:39] [eWeLink] A total of [0] accessories were loaded from the local cache
[2018-3-28 23:59:39] [eWeLink] Requesting a list of devices from eWeLink HTTPS API at [https://eu-api.coolkit.cc:8080]
[2018-3-28 23:59:39] Homebridge is running on port 51826.
[2018-3-28 23:59:40] [eWeLink] eWeLink HTTPS API reports that there are a total of [1] devices registered
[2018-3-28 23:59:40] [eWeLink] Evaluating if devices need to be removed...
[2018-3-28 23:59:40] [eWeLink] Evaluating if new devices need to be added...
[2018-3-28 23:59:40] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH1] will be added
[2018-3-28 23:59:40] [eWeLink] Found Accessory with Name : [Tapparella 1 CH 1], Manufacturer : [Sonoff 4CH Pro], Status : [on], Is Online : [true], API Key: [***]
[2018-3-28 23:59:40] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH2] will be added
[2018-3-28 23:59:40] [eWeLink] Found Accessory with Name : [Tapparella 1 CH 2], Manufacturer : [Sonoff 4CH Pro], Status : [off], Is Online : [true], API Key: [***]
[2018-3-28 23:59:40] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH3] will be added
[2018-3-28 23:59:40] [eWeLink] Found Accessory with Name : [Tapparella 1 CH 3], Manufacturer : [Sonoff 4CH Pro], Status : [off], Is Online : [true], API Key: [***]
[2018-3-28 23:59:40] [eWeLink] Device [Tapparella 1], ID : [1000209aa1CH4] will be added
[2018-3-28 23:59:40] [eWeLink] Found Accessory with Name : [Tapparella 1 CH 4], Manufacturer : [Sonoff 4CH Pro], Status : [off], Is Online : [true], API Key: [***]
[2018-3-28 23:59:40] [eWeLink] API key retrieved from web service is [***]
[2018-3-28 23:59:40] [eWeLink] Connecting to the WebSocket API at [wss://eu-long.coolkit.cc:8080/api/ws]
[2018-3-28 23:59:40] [eWeLink] Sending login request [{"action":"userOnline","userAgent":"app","version":6,"nonce":"152227438048800","apkVesrion":"1.8","os":"ios","at":"ec863ac2bec17ae7d21d57ba29a8054d9218da19","apikey":"***","ts":"1522274380","model":"iPhone10,6","romVersion":"11.1.2","sequence":1522274380488}]

```


I'll link here also the platform related to the plugin:


```
{
                        "platform": "eWeLink",
                        "name": "eWeLink",
                        "authenticationToken": "******Found with Charles...*****",
                        "apiHost": "eu-api.coolkit.cc:8080",
                        "webSocketApi": "eu-long.coolkit.cc"
                }
 
```
I tried to change the websocketApi to "us-" but it also get stuck.
```
[2018-3-29 00:06:16] [eWeLink] Connecting to the WebSocket API at [wss://us-long.coolkit.cc:8080/api/ws]
[2018-3-29 00:06:17] [eWeLink] Sending login request [{"action":"userOnline","userAgent":"app","version":6,"nonce":"152227477737400","apkVesrion":"1.8","os":"ios","at":"ec863ac2bec17ae7d21d57ba29a8054d9218da19","apikey":"*****","ts":"1522274777","model":"iPhone10,6","romVersion":"11.1.2","sequence":1522274777374}]
```

**Comment by aremishevsky** [comment]
Following URLs work for me fine: 
```json
{
   "platform": "eWeLink",
   "name": "eWeLink",
   "authenticationToken": "******...*****",
   "apiHost"            : "eu-api.coolkit.cc:8080",
   "webSocketApi" : "eu-long.coolkit.cc"
}
```
 @Trivellacipi  try to use "us" endpoints
```json
{
   "apiHost"            : "us-api.coolkit.cc:8080",
   "webSocketApi" : "us-long.coolkit.cc"
}
```

If that would not help - re-login in your app using Charles proxy (update your token). And note with what domain URL (us/eu/...) it works from original eWeLink app (in Charles) - that domain you should use as well.
But this is an another story/issue.
**P.S. Do not forger before every try to cleanup of your cached accessories.**

**Comment by Trivellacipi** [comment]
There is something wrong with my situation. 

Here is the output trying the "eu" case: 

```
2:14] [eWeLink] WebSocket was closed. Reason [1006]
WebSocketClient: reconnecting...

```

And the same output happens if i put "us" only in the websocketApi. ("us" also in the apiHost will thrown an error earlier)

I disabled entirely the firewall on my current machine, but i'm thinking about something in the router. Maybe i need some port forwarding to receive the the Ack back from the server.

**Comment by aremishevsky** [comment]
@Trivellacipi does your switches work now?
(ignore 1006 reason - it's another issue with re-connect https://github.com/gbro115/homebridge-ewelink/issues/11 )

**Comment by 18066034545** [comment]
BN-C04-4

**Comment by 18066034545** [comment]
谢谢您

**Comment by aremishevsky** [comment]
@18066034545 
Please send it in format:
"XXX-XXX-XX" - 2 switches
"XXX-XXX-XX" - 3 switches
"XXX-XXX-XX" - 4 switches

**Comment by Trivellacipi** [comment]
Unfortunately they are not working because the entire homebridge server seems to be stopped. 
Homekit accessories in the Home app show up an “updating” status forever

**Comment by aremishevsky** [comment]
@Trivellacipi try to remove cached accessories and restart your homebridge.
If that would not help - remove completely all ~/.homebridge folder (remove the bridge from HomeKit App first). Restart your server with your new config.

**Comment by Trivellacipi** [comment]
I spent days trying to find out what was wrong.
I installed homebridge on my raspberry, which is also used as a web server. So, to protect myself i installed and set up a firewall which was blocking all responses from the Websocket. Now that i disabled the firewall all it's going right. 
Do you know which port i need to open in my local firewall to enable communication with the webserver? i already tried 8080 with any result.

**Comment by FlyingKiwiJosh** [comment]
Hi wondering if you could add the following as I can only get 2 channels to show up with eWeLink-plus

PSF-B04-GL it’s a 3 gang light switch

**Comment by Magutibasilio** [comment]
Hello, I have a 4ch pro sonoff and I can not detect it after installing npm i -g git+https://github.com/aremishevsky/homebridge-ewelink, could you help me?

**Comment by kalety** [comment]
Hi!, the problem seems to be that homekit gives the same model to a sonoff dual than sonoff 4ch pro, PSF-B04-GL. Hope this help!

**Comment by Magutibasilio** [comment]
And what can I do to solve it ?, or there is no solution?
