### ISSUE TITLE
EAKCB-EWE-M circuit breaker support

### ISSUE THREAD

**Issue by itaiLandau** [bwp91/homebridge-ewelink#636]
[T1-Balcony] is not supported, do create a GitHub issue with the following info:
[226] {"bindInfos":{},"version":8,"rssi":-98,"fwVersion":"1.0.0","totalPower":0,"phase_0_c":0,"phase_0_v":229.95,"phase_0_p":0,"availablePower":0,"switch":true,"pulse":"off","pulseWidth":1000,"sledOnline":"on","startup":"off","prepaid_support":true,"alarm_v_min":210,"alarm_v_max":250,"alarm_c_min":-1,"alarm_c_max":-1,"alarm_p_min":-1,"alarm_p_max":100,"prepaidEnale":false,"prepaidLowBalanceAlert":false,"prepaidLowest":0,"min_p_upper":5000,"min_p_lower":1,"max_p_upper":15000,"max_p_lower":1,"min_v_upper":220,"min_v_lower":76,"max_v_upper":300,"max_v_lower":220,"max_c_upper":63,"max_c_lower":0.1,"calibrateFlag":false,"ssid":"Landau IoT","bssid":"A6:05:D6:49:A8:72","staMac":"D0:27:03:BF:72:58","uiActive":60,"hundredDaysKwh":"get","alarmType":"pv","timers":[{"mId":"17fdcafb-b552-468e-b643-3197b6e3dbb5","coolkit_timer_type":"repeat","enabled":1,"do":{"switch":false},"type":"repeat","at":"30 22 * * 0,1,2,3,4,5,6"}]}.

I installed 6 of these new circuit breakers and they seem to not be supported even though I have 4 other versions of these circuit breakers from the same company which are supported.
please let me know if the details of the other 5 devices can help and I'll send them as well.

link to the product on Aliexpress: [https://a.aliexpress.com/_oCkd1pz](https://a.aliexpress.com/_oCkd1pz)

**Comment by itaiLandau** [comment]
I saw you updated the plugin to add support for these devices and they do showup in homekit now but unfortunately they do not respond to commands nor show the true status in HomeKit. I get the following error messege in the plugin logs when trying to interact with any of them:
[eWeLink] [T1-Balcony] device update failed as unknown WS response [400] at default.sendUpdate (file:///homebridge/node_modules/@homebridge-plugins/homebridge-ewelink/lib/connection/ws.js:338:19) at default.sendUpdate (file:///homebridge/node_modules/@homebridge-plugins/homebridge-ewelink/lib/connection/ws.js:342:15).
