### ISSUE TITLE
eWeLink synchronisation error

### ISSUE THREAD

**Issue by satang456** [bwp91/homebridge-ewelink#72]
[8/19/2020, 2:37:56 PM] [eWeLink] ** eWeLink synchronisation error: **
[8/19/2020, 2:37:56 PM] [eWeLink] TypeError: Cannot read property 'uiid' of undefined
    at eWeLink.initialiseDevice (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:130:27)
    at devicesInEwe.forEach.device (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:104:27)
    at Map.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:103:37
    at httpClient.getHost.then.then.then.then.then.then.res (/usr/local/lib/node_modules/homebridge-ewelink/lib/eWeLink.js:118:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[8/19/2020, 2:37:56 PM] [eWeLink] ** Plugin will not be loaded. **
[8/19/2020, 2:37:58 PM] [eWeLink] Web socket closed - [1006].
[8/19/2020, 2:37:58 PM] [eWeLink] Web socket will try to reconnect in five seconds then try the command again.

**config file**
{
            "name": "eWeLink",
            "countryCode": "66",
            "username": "xxxxxxx",
            "password": "xxxxxxx",
            "debug": false,
            "debugReqRes": false,
            "mode": "ws",
            "sensorTimeLength": 2,
            "sensorTimeDifference": 120,
            "valveTimeLength": 20,
            "hideZBLDPress": false,
            "groups": [
                {
                    "type": "null",
                    "setup": "null",
                    "operationTime": 100,
                    "inched": true
                }
            ],
            "bridgeSensors": [
                {
                    "type": "motion"
                }
            ],
            "platform": "eWeLink"
        }

**Comment by bwp91** [comment]
Can I ask which ewelink devices you have?
Also please send me the previous few lines of the log before the error as this can often help me locate issues.
Thanks
Ben

**Comment by satang456** [comment]
**### Devices** 
I have Switches basic and Light Switches TX-3C.

**### Log**
[8/19/2020, 2:37:45 PM] [HB Supervisor] Starting Homebridge with extra flags: -I
[8/19/2020, 2:37:45 PM] [HB Supervisor] Started Homebridge v1.1.2 with PID: 9412
[8/19/2020, 2:37:47 PM] Loaded config.json with 0 accessories and 2 platforms.
[8/19/2020, 2:37:47 PM] ---
[8/19/2020, 2:37:49 PM] Loaded plugin: homebridge-config-ui-x@4.26.0
[8/19/2020, 2:37:49 PM] Registering platform 'homebridge-config-ui-x.config'
[8/19/2020, 2:37:49 PM] ---
[8/19/2020, 2:37:49 PM] Loaded plugin: homebridge-ewelink@2.19.2
[8/19/2020, 2:37:50 PM] Registering platform 'homebridge-ewelink.eWeLink'
[8/19/2020, 2:37:50 PM] ---
[8/19/2020, 2:37:50 PM] Loading 2 platforms...
[8/19/2020, 2:37:50 PM] [Config] Initializing config platform...
[8/19/2020, 2:37:50 PM] [Config] Running in Service Mode
[8/19/2020, 2:37:50 PM] [eWeLink] Initializing eWeLink platform...
[8/19/2020, 2:37:50 PM] [eWeLink] Plugin has finished initialising. Starting synchronisation with eWeLink account.
Setup Payload:
X-HM://0023QJ31LDCJO
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │xxx-xx-xxx│     
    └────────────┘     
                       
[8/19/2020, 2:37:50 PM] Homebridge is running on port 51152.
[8/19/2020, 2:37:56 PM] [eWeLink] [0] eWeLink devices were loaded from the Homebridge cache.
[8/19/2020, 2:37:56 PM] [eWeLink] [7] primary devices were loaded from your eWeLink account.
[8/19/2020, 2:37:56 PM] [eWeLink] [7] primary devices were discovered on your local network.

**Comment by bwp91** [comment]
Would you be happy to share your devices with my ewelink account?
I won't need to control them but it's just the quickest way for me to see what's going wrong.
If you are happy then I would also need to know which country you are based in?
Thanks

**Comment by bwp91** [comment]
If not we can find another way :)

**Comment by bwp91** [comment]
@satang456 if you update to v2.19.3 it might give a little more insight in the logs as to whats going on.

**Comment by bozzy01** [comment]
I am having the same "Synchronisation" error , log below: (added a 2nd log from a restart as well)

### Devices

Just an in wall switch 

### LOG

[8/19/2020, 8:57:41 PM] [eWeLink] ** eWeLink synchronisation error: **
[8/19/2020, 8:57:41 PM] [eWeLink] Error: getaddrinfo EAI_AGAIN us-apia.coolkit.cc
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'us-apia.coolkit.cc',
  config: {
    url: 'https://us-apia.coolkit.cc/v2/user/login',
    method: 'post',
    data: '{"countryCode":"+1","password":"XXXX","email":"XXXX"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Authorization: 'Sign xEIKn30x3fovrX01NBzjfUdYe1S0gIx/pGFAx2IiuYI=',
      Host: 'us-apia.coolkit.cc',
      'X-CK-Appid': 'oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq',
      'X-CK-Nonce': 'nvh7h3vw',
      'User-Agent': 'axios/0.19.2',
      'Content-Length': 70
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    _options: {
      protocol: 'https:',
      maxRedirects: 21,
      maxBodyLength: 10485760,
      path: '/v2/user/login',
      method: 'POST',
      headers: [Object],
      agent: undefined,
      agents: [Object],
      auth: undefined,
      hostname: 'us-apia.coolkit.cc',
      port: null,
      nativeProtocols: [Object],
      pathname: '/v2/user/login'
    },
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 70,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'POST /v2/user/login HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Authorization: Sign xEIKn30x3fovrX01NBzjfUdYe1S0gIx/pGFAx2IiuYI=\r\n' +
        'Host: us-apia.coolkit.cc\r\n' +
        'X-CK-Appid: oeVkj2lYFGnJu5XUtWisfW4utiN4u9Mq\r\n' +
        'X-CK-Nonce: nvh7h3vw\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Content-Length: 70\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      insecureHTTPParser: undefined,
      path: '/v2/user/login',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Circular],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'https://us-apia.coolkit.cc/v2/user/login',
    [Symbol(kCapture)]: false
  },
  response: undefined,
  isAxiosError: true,
  toJSON: [Function]
}
[8/19/2020, 8:57:41 PM] [eWeLink] ** Plugin will not be loaded. **

### Log restarted homebridge now this:

[8/19/2020, 9:03:42 PM] [eWeLink] Server did not respond with an authentication token. Please double check your eWeLink username and password in the Homebridge configuration.
{
  "error": 500,
  "msg": "init failed",
  "data": {}
}

**Comment by satang456** [comment]
I update v 2.19.3 Devices sync .
when change name devices in app eWeLink not update into homebridge-ewelink and homebridge ewelink very slow websocket.

### **The problem in this VDO.**
https://drive.google.com/file/d/1jf3AEPQen8nOR6WVIOvxMGqDiYYbaisj/view?usp=sharing

**Comment by bwp91** [comment]
Please try in the config changing the line:

`"mode": "ws",`

to

`"mode": "lan",`

And let me know if it's faster

**Comment by bwp91** [comment]
also, this plugin doesn't support synchronising device names between Homebridge and the eWeLink app

**Comment by satang456** [comment]
thank you so much

**Comment by bwp91** [comment]
Has this made it faster?

**Comment by bwp91** [comment]
Please let me know if you're happy for me to close this issue.
Thanks!
